/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// ConfirmUploadDto
    /// </summary>
    [DataContract(Name = "ConfirmUploadDto")]
    public partial class ConfirmUploadDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmUploadDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfirmUploadDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmUploadDto" /> class.
        /// </summary>
        /// <param name="fileId">File ID returned from upload URL request (required).</param>
        /// <param name="checksum">File checksum for integrity verification.</param>
        /// <param name="size">Actual file size in bytes.</param>
        public ConfirmUploadDto(string fileId = default, string checksum = default, decimal size = default)
        {
            // to ensure "fileId" is required (not null)
            if (fileId == null)
            {
                throw new ArgumentNullException("fileId is a required property for ConfirmUploadDto and cannot be null");
            }
            this.FileId = fileId;
            this.Checksum = checksum;
            this.Size = size;
        }

        /// <summary>
        /// File ID returned from upload URL request
        /// </summary>
        /// <value>File ID returned from upload URL request</value>
        [DataMember(Name = "fileId", IsRequired = true, EmitDefaultValue = true)]
        public string FileId { get; set; }

        /// <summary>
        /// File checksum for integrity verification
        /// </summary>
        /// <value>File checksum for integrity verification</value>
        [DataMember(Name = "checksum", EmitDefaultValue = false)]
        public string Checksum { get; set; }

        /// <summary>
        /// Actual file size in bytes
        /// </summary>
        /// <value>Actual file size in bytes</value>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public decimal Size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfirmUploadDto {\n");
            sb.Append("  FileId: ").Append(FileId).Append("\n");
            sb.Append("  Checksum: ").Append(Checksum).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
