/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// CreatePaymentMethodDto
    /// </summary>
    [DataContract(Name = "CreatePaymentMethodDto")]
    public partial class CreatePaymentMethodDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePaymentMethodDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePaymentMethodDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePaymentMethodDto" /> class.
        /// </summary>
        /// <param name="customerId">customerId (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="isDefault">isDefault.</param>
        /// <param name="cardNumber">cardNumber.</param>
        /// <param name="brand">brand.</param>
        /// <param name="last4">last4.</param>
        /// <param name="expiryMonth">expiryMonth.</param>
        /// <param name="expiryYear">expiryYear.</param>
        public CreatePaymentMethodDto(string customerId = default, string type = default, bool isDefault = default, string cardNumber = default, string brand = default, string last4 = default, decimal expiryMonth = default, decimal expiryYear = default)
        {
            // to ensure "customerId" is required (not null)
            if (customerId == null)
            {
                throw new ArgumentNullException("customerId is a required property for CreatePaymentMethodDto and cannot be null");
            }
            this.CustomerId = customerId;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for CreatePaymentMethodDto and cannot be null");
            }
            this.Type = type;
            this.IsDefault = isDefault;
            this.CardNumber = cardNumber;
            this.Brand = brand;
            this.Last4 = last4;
            this.ExpiryMonth = expiryMonth;
            this.ExpiryYear = expiryYear;
        }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", IsRequired = true, EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets IsDefault
        /// </summary>
        [DataMember(Name = "isDefault", EmitDefaultValue = true)]
        public bool IsDefault { get; set; }

        /// <summary>
        /// Gets or Sets CardNumber
        /// </summary>
        [DataMember(Name = "cardNumber", EmitDefaultValue = false)]
        public string CardNumber { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Last4
        /// </summary>
        [DataMember(Name = "last4", EmitDefaultValue = false)]
        public string Last4 { get; set; }

        /// <summary>
        /// Gets or Sets ExpiryMonth
        /// </summary>
        [DataMember(Name = "expiryMonth", EmitDefaultValue = false)]
        public decimal ExpiryMonth { get; set; }

        /// <summary>
        /// Gets or Sets ExpiryYear
        /// </summary>
        [DataMember(Name = "expiryYear", EmitDefaultValue = false)]
        public decimal ExpiryYear { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePaymentMethodDto {\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  IsDefault: ").Append(IsDefault).Append("\n");
            sb.Append("  CardNumber: ").Append(CardNumber).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Last4: ").Append(Last4).Append("\n");
            sb.Append("  ExpiryMonth: ").Append(ExpiryMonth).Append("\n");
            sb.Append("  ExpiryYear: ").Append(ExpiryYear).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
