/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// CreatePayoutDto
    /// </summary>
    [DataContract(Name = "CreatePayoutDto")]
    public partial class CreatePayoutDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePayoutDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePayoutDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePayoutDto" /> class.
        /// </summary>
        /// <param name="merchantId">The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant..</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="bankAccount">bankAccount.</param>
        /// <param name="description">description.</param>
        /// <param name="metadata">metadata (required).</param>
        public CreatePayoutDto(string merchantId = default, decimal amount = default, string currency = default, string bankAccount = default, string description = default, Dictionary<string, Object> metadata = default)
        {
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CreatePayoutDto and cannot be null");
            }
            this.Currency = currency;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for CreatePayoutDto and cannot be null");
            }
            this.Metadata = metadata;
            this.MerchantId = merchantId;
            this.BankAccount = bankAccount;
            this.Description = description;
        }

        /// <summary>
        /// The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
        /// </summary>
        /// <value>The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.</value>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets BankAccount
        /// </summary>
        [DataMember(Name = "bankAccount", EmitDefaultValue = false)]
        public string BankAccount { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        /*
        <example>{&quot;orderId&quot;:&quot;12345&quot;}</example>
        */
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePayoutDto {\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  BankAccount: ").Append(BankAccount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
