/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// CustomerStatsDto
    /// </summary>
    [DataContract(Name = "CustomerStatsDto")]
    public partial class CustomerStatsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerStatsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CustomerStatsDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerStatsDto" /> class.
        /// </summary>
        /// <param name="daily">New customers in the last 24 hours (required).</param>
        /// <param name="weekly">New customers in the last 7 days (required).</param>
        /// <param name="monthly">New customers in the last 30 days (required).</param>
        public CustomerStatsDto(decimal daily = default, decimal weekly = default, decimal monthly = default)
        {
            this.Daily = daily;
            this.Weekly = weekly;
            this.Monthly = monthly;
        }

        /// <summary>
        /// New customers in the last 24 hours
        /// </summary>
        /// <value>New customers in the last 24 hours</value>
        [DataMember(Name = "daily", IsRequired = true, EmitDefaultValue = true)]
        public decimal Daily { get; set; }

        /// <summary>
        /// New customers in the last 7 days
        /// </summary>
        /// <value>New customers in the last 7 days</value>
        [DataMember(Name = "weekly", IsRequired = true, EmitDefaultValue = true)]
        public decimal Weekly { get; set; }

        /// <summary>
        /// New customers in the last 30 days
        /// </summary>
        /// <value>New customers in the last 30 days</value>
        [DataMember(Name = "monthly", IsRequired = true, EmitDefaultValue = true)]
        public decimal Monthly { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomerStatsDto {\n");
            sb.Append("  Daily: ").Append(Daily).Append("\n");
            sb.Append("  Weekly: ").Append(Weekly).Append("\n");
            sb.Append("  Monthly: ").Append(Monthly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
