/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// FileDto
    /// </summary>
    [DataContract(Name = "FileDto")]
    public partial class FileDto : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Uploaded for value: uploaded
            /// </summary>
            [EnumMember(Value = "uploaded")]
            Uploaded = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 3,

            /// <summary>
            /// Enum Deleted for value: deleted
            /// </summary>
            [EnumMember(Value = "deleted")]
            Deleted = 4
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FileDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FileDto" /> class.
        /// </summary>
        /// <param name="id">Unique identifier (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="deletedAt">deletedAt.</param>
        /// <param name="key">key (required).</param>
        /// <param name="bucket">bucket (required).</param>
        /// <param name="filename">filename (required).</param>
        /// <param name="mimeType">mimeType (required).</param>
        /// <param name="size">size (required).</param>
        /// <param name="tags">tags (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="checksum">checksum.</param>
        /// <param name="isPublic">isPublic (required).</param>
        /// <param name="relatedEntityId">relatedEntityId.</param>
        /// <param name="relatedEntityType">relatedEntityType.</param>
        /// <param name="uploadedById">uploadedById.</param>
        public FileDto(string id = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default, DateTimeOffset deletedAt = default, string key = default, string bucket = default, string filename = default, string mimeType = default, decimal size = default, List<string> tags = default, StatusEnum status = default, string checksum = default, bool isPublic = default, string relatedEntityId = default, string relatedEntityType = default, string uploadedById = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FileDto and cannot be null");
            }
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for FileDto and cannot be null");
            }
            this.Key = key;
            // to ensure "bucket" is required (not null)
            if (bucket == null)
            {
                throw new ArgumentNullException("bucket is a required property for FileDto and cannot be null");
            }
            this.Bucket = bucket;
            // to ensure "filename" is required (not null)
            if (filename == null)
            {
                throw new ArgumentNullException("filename is a required property for FileDto and cannot be null");
            }
            this.Filename = filename;
            // to ensure "mimeType" is required (not null)
            if (mimeType == null)
            {
                throw new ArgumentNullException("mimeType is a required property for FileDto and cannot be null");
            }
            this.MimeType = mimeType;
            this.Size = size;
            // to ensure "tags" is required (not null)
            if (tags == null)
            {
                throw new ArgumentNullException("tags is a required property for FileDto and cannot be null");
            }
            this.Tags = tags;
            this.Status = status;
            this.IsPublic = isPublic;
            this.DeletedAt = deletedAt;
            this.Checksum = checksum;
            this.RelatedEntityId = relatedEntityId;
            this.RelatedEntityType = relatedEntityType;
            this.UploadedById = uploadedById;
        }

        /// <summary>
        /// Unique identifier
        /// </summary>
        /// <value>Unique identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets DeletedAt
        /// </summary>
        [DataMember(Name = "deletedAt", EmitDefaultValue = false)]
        public DateTimeOffset DeletedAt { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets Bucket
        /// </summary>
        [DataMember(Name = "bucket", IsRequired = true, EmitDefaultValue = true)]
        public string Bucket { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", IsRequired = true, EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Gets or Sets MimeType
        /// </summary>
        [DataMember(Name = "mimeType", IsRequired = true, EmitDefaultValue = true)]
        public string MimeType { get; set; }

        /// <summary>
        /// Gets or Sets Size
        /// </summary>
        [DataMember(Name = "size", IsRequired = true, EmitDefaultValue = true)]
        public decimal Size { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets Checksum
        /// </summary>
        [DataMember(Name = "checksum", EmitDefaultValue = false)]
        public string Checksum { get; set; }

        /// <summary>
        /// Gets or Sets IsPublic
        /// </summary>
        [DataMember(Name = "isPublic", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPublic { get; set; }

        /// <summary>
        /// Gets or Sets RelatedEntityId
        /// </summary>
        [DataMember(Name = "relatedEntityId", EmitDefaultValue = false)]
        public string RelatedEntityId { get; set; }

        /// <summary>
        /// Gets or Sets RelatedEntityType
        /// </summary>
        [DataMember(Name = "relatedEntityType", EmitDefaultValue = false)]
        public string RelatedEntityType { get; set; }

        /// <summary>
        /// Gets or Sets UploadedById
        /// </summary>
        [DataMember(Name = "uploadedById", EmitDefaultValue = false)]
        public string UploadedById { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  DeletedAt: ").Append(DeletedAt).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Bucket: ").Append(Bucket).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  MimeType: ").Append(MimeType).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Checksum: ").Append(Checksum).Append("\n");
            sb.Append("  IsPublic: ").Append(IsPublic).Append("\n");
            sb.Append("  RelatedEntityId: ").Append(RelatedEntityId).Append("\n");
            sb.Append("  RelatedEntityType: ").Append(RelatedEntityType).Append("\n");
            sb.Append("  UploadedById: ").Append(UploadedById).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
