/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// ImpersonateUserDto
    /// </summary>
    [DataContract(Name = "ImpersonateUserDto")]
    public partial class ImpersonateUserDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpersonateUserDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImpersonateUserDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImpersonateUserDto" /> class.
        /// </summary>
        /// <param name="userId">The ID of the user to impersonate (required).</param>
        public ImpersonateUserDto(string userId = default)
        {
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for ImpersonateUserDto and cannot be null");
            }
            this.UserId = userId;
        }

        /// <summary>
        /// The ID of the user to impersonate
        /// </summary>
        /// <value>The ID of the user to impersonate</value>
        /*
        <example>user_12345</example>
        */
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImpersonateUserDto {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
