/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// ListMembersResponseDto
    /// </summary>
    [DataContract(Name = "ListMembersResponseDto")]
    public partial class ListMembersResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListMembersResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ListMembersResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListMembersResponseDto" /> class.
        /// </summary>
        /// <param name="members">List of organization members (required).</param>
        public ListMembersResponseDto(List<MemberDto> members = default)
        {
            // to ensure "members" is required (not null)
            if (members == null)
            {
                throw new ArgumentNullException("members is a required property for ListMembersResponseDto and cannot be null");
            }
            this.Members = members;
        }

        /// <summary>
        /// List of organization members
        /// </summary>
        /// <value>List of organization members</value>
        [DataMember(Name = "members", IsRequired = true, EmitDefaultValue = true)]
        public List<MemberDto> Members { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListMembersResponseDto {\n");
            sb.Append("  Members: ").Append(Members).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
