/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Sdk.Client.OpenAPIDateConverter;

namespace Cashful.Sdk.Model
{
    /// <summary>
    /// ResetPasswordResponseDto
    /// </summary>
    [DataContract(Name = "ResetPasswordResponseDto")]
    public partial class ResetPasswordResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResetPasswordResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResetPasswordResponseDto" /> class.
        /// </summary>
        /// <param name="success">Password reset successfully (required).</param>
        public ResetPasswordResponseDto(bool success = default)
        {
            this.Success = success;
        }

        /// <summary>
        /// Password reset successfully
        /// </summary>
        /// <value>Password reset successfully</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "success", IsRequired = true, EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResetPasswordResponseDto {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
