/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cashful.Client;
using Cashful.Model;

namespace Cashful.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Event
        /// </summary>
        /// <remarks>
        /// Records a new event and triggers associated webhooks.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <returns></returns>
        void CreateEvent(CreateEventDto createEventDto);

        /// <summary>
        /// Create Event
        /// </summary>
        /// <remarks>
        /// Records a new event and triggers associated webhooks.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateEventWithHttpInfo(CreateEventDto createEventDto);
        /// <summary>
        /// List Event Types
        /// </summary>
        /// <remarks>
        /// Retrieves all available event types that can be sent or subscribed to.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListEventTypesResponseDto</returns>
        ListEventTypesResponseDto ListEventTypes();

        /// <summary>
        /// List Event Types
        /// </summary>
        /// <remarks>
        /// Retrieves all available event types that can be sent or subscribed to.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListEventTypesResponseDto</returns>
        ApiResponse<ListEventTypesResponseDto> ListEventTypesWithHttpInfo();
        /// <summary>
        /// List Events
        /// </summary>
        /// <remarks>
        /// Retrieves a log of all API events for debugging and logging.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <returns>ListEventsResponseDto</returns>
        ListEventsResponseDto ListEvents(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default);

        /// <summary>
        /// List Events
        /// </summary>
        /// <remarks>
        /// Retrieves a log of all API events for debugging and logging.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <returns>ApiResponse of ListEventsResponseDto</returns>
        ApiResponse<ListEventsResponseDto> ListEventsWithHttpInfo(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Event
        /// </summary>
        /// <remarks>
        /// Records a new event and triggers associated webhooks.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateEventAsync(CreateEventDto createEventDto, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Event
        /// </summary>
        /// <remarks>
        /// Records a new event and triggers associated webhooks.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateEventWithHttpInfoAsync(CreateEventDto createEventDto, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List Event Types
        /// </summary>
        /// <remarks>
        /// Retrieves all available event types that can be sent or subscribed to.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListEventTypesResponseDto</returns>
        System.Threading.Tasks.Task<ListEventTypesResponseDto> ListEventTypesAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List Event Types
        /// </summary>
        /// <remarks>
        /// Retrieves all available event types that can be sent or subscribed to.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListEventTypesResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListEventTypesResponseDto>> ListEventTypesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List Events
        /// </summary>
        /// <remarks>
        /// Retrieves a log of all API events for debugging and logging.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListEventsResponseDto</returns>
        System.Threading.Tasks.Task<ListEventsResponseDto> ListEventsAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List Events
        /// </summary>
        /// <remarks>
        /// Retrieves a log of all API events for debugging and logging.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListEventsResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListEventsResponseDto>> ListEventsWithHttpInfoAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEventsApi : IEventsApiSync, IEventsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EventsApi : IDisposable, IEventsApi
    {
        private Cashful.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public EventsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public EventsApi(string basePath)
        {
            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                new Cashful.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public EventsApi(Cashful.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EventsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EventsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                new Cashful.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public EventsApi(HttpClient client, Cashful.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EventsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public EventsApi(Cashful.Client.ISynchronousClient client, Cashful.Client.IAsynchronousClient asyncClient, Cashful.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cashful.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cashful.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cashful.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cashful.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cashful.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Event Records a new event and triggers associated webhooks.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <returns></returns>
        public void CreateEvent(CreateEventDto createEventDto)
        {
            CreateEventWithHttpInfo(createEventDto);
        }

        /// <summary>
        /// Create Event Records a new event and triggers associated webhooks.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Cashful.Client.ApiResponse<Object> CreateEventWithHttpInfo(CreateEventDto createEventDto)
        {
            // verify the required parameter 'createEventDto' is set
            if (createEventDto == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'createEventDto' when calling EventsApi->CreateEvent");

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createEventDto;

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/api/canary/events", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateEvent", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Event Records a new event and triggers associated webhooks.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateEventAsync(CreateEventDto createEventDto, System.Threading.CancellationToken cancellationToken = default)
        {
            await CreateEventWithHttpInfoAsync(createEventDto, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Create Event Records a new event and triggers associated webhooks.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEventDto"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<Object>> CreateEventWithHttpInfoAsync(CreateEventDto createEventDto, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createEventDto' is set
            if (createEventDto == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'createEventDto' when calling EventsApi->CreateEvent");


            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createEventDto;

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/api/canary/events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateEvent", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Event Types Retrieves all available event types that can be sent or subscribed to.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListEventTypesResponseDto</returns>
        public ListEventTypesResponseDto ListEventTypes()
        {
            Cashful.Client.ApiResponse<ListEventTypesResponseDto> localVarResponse = ListEventTypesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Event Types Retrieves all available event types that can be sent or subscribed to.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListEventTypesResponseDto</returns>
        public Cashful.Client.ApiResponse<ListEventTypesResponseDto> ListEventTypesWithHttpInfo()
        {
            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListEventTypesResponseDto>("/api/canary/events/types", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEventTypes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Event Types Retrieves all available event types that can be sent or subscribed to.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListEventTypesResponseDto</returns>
        public async System.Threading.Tasks.Task<ListEventTypesResponseDto> ListEventTypesAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Client.ApiResponse<ListEventTypesResponseDto> localVarResponse = await ListEventTypesWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Event Types Retrieves all available event types that can be sent or subscribed to.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListEventTypesResponseDto)</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<ListEventTypesResponseDto>> ListEventTypesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListEventTypesResponseDto>("/api/canary/events/types", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEventTypes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Events Retrieves a log of all API events for debugging and logging.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <returns>ListEventsResponseDto</returns>
        public ListEventsResponseDto ListEvents(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default)
        {
            Cashful.Client.ApiResponse<ListEventsResponseDto> localVarResponse = ListEventsWithHttpInfo(merchantId, limit, offset, filter, sort, order, type, status, startDate, endDate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Events Retrieves a log of all API events for debugging and logging.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <returns>ApiResponse of ListEventsResponseDto</returns>
        public Cashful.Client.ApiResponse<ListEventsResponseDto> ListEventsWithHttpInfo(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'merchantId' when calling EventsApi->ListEvents");

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (order != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "order", order));
            }
            localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "merchantId", merchantId));
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListEventsResponseDto>("/api/canary/events", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Events Retrieves a log of all API events for debugging and logging.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListEventsResponseDto</returns>
        public async System.Threading.Tasks.Task<ListEventsResponseDto> ListEventsAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Client.ApiResponse<ListEventsResponseDto> localVarResponse = await ListEventsWithHttpInfoAsync(merchantId, limit, offset, filter, sort, order, type, status, startDate, endDate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Events Retrieves a log of all API events for debugging and logging.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The ID of the merchant whose events are being requested. This parameter is required.</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="filter">JSON string used for dynamic filtering (optional)</param>
        /// <param name="sort">Field name to sort by (optional)</param>
        /// <param name="order">Sort direction (ASC or DESC) (optional)</param>
        /// <param name="type">Filter by event type (optional)</param>
        /// <param name="status">Filter by event status (optional)</param>
        /// <param name="startDate">Filter by start date (optional)</param>
        /// <param name="endDate">Filter by end date (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListEventsResponseDto)</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<ListEventsResponseDto>> ListEventsWithHttpInfoAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? filter = default, string? sort = default, string? order = default, string? type = default, string? status = default, string? startDate = default, string? endDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'merchantId' when calling EventsApi->ListEvents");


            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "sort", sort));
            }
            if (order != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "order", order));
            }
            localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "merchantId", merchantId));
            if (type != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "type", type));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (startDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "startDate", startDate));
            }
            if (endDate != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "endDate", endDate));
            }

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListEventsResponseDto>("/api/canary/events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEvents", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
