/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cashful.Client;
using Cashful.Model;

namespace Cashful.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete Payment Method
        /// </summary>
        /// <remarks>
        /// Detaches and deletes a saved payment method from a customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>Object</returns>
        Object DeletePaymentMethod(string id);

        /// <summary>
        /// Delete Payment Method
        /// </summary>
        /// <remarks>
        /// Detaches and deletes a saved payment method from a customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeletePaymentMethodWithHttpInfo(string id);
        /// <summary>
        /// List Payment Methods
        /// </summary>
        /// <remarks>
        /// Lists saved payment methods for a specific customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <returns>ListPaymentMethodsResponseDto</returns>
        ListPaymentMethodsResponseDto ListPaymentMethods(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default);

        /// <summary>
        /// List Payment Methods
        /// </summary>
        /// <remarks>
        /// Lists saved payment methods for a specific customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <returns>ApiResponse of ListPaymentMethodsResponseDto</returns>
        ApiResponse<ListPaymentMethodsResponseDto> ListPaymentMethodsWithHttpInfo(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default);
        /// <summary>
        /// Retrieve Payment Method
        /// </summary>
        /// <remarks>
        /// Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>PaymentMethodResponseDto</returns>
        PaymentMethodResponseDto RetrievePaymentMethod(string id);

        /// <summary>
        /// Retrieve Payment Method
        /// </summary>
        /// <remarks>
        /// Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>ApiResponse of PaymentMethodResponseDto</returns>
        ApiResponse<PaymentMethodResponseDto> RetrievePaymentMethodWithHttpInfo(string id);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete Payment Method
        /// </summary>
        /// <remarks>
        /// Detaches and deletes a saved payment method from a customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeletePaymentMethodAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete Payment Method
        /// </summary>
        /// <remarks>
        /// Detaches and deletes a saved payment method from a customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeletePaymentMethodWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List Payment Methods
        /// </summary>
        /// <remarks>
        /// Lists saved payment methods for a specific customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPaymentMethodsResponseDto</returns>
        System.Threading.Tasks.Task<ListPaymentMethodsResponseDto> ListPaymentMethodsAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List Payment Methods
        /// </summary>
        /// <remarks>
        /// Lists saved payment methods for a specific customer.
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPaymentMethodsResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListPaymentMethodsResponseDto>> ListPaymentMethodsWithHttpInfoAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Retrieve Payment Method
        /// </summary>
        /// <remarks>
        /// Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentMethodResponseDto</returns>
        System.Threading.Tasks.Task<PaymentMethodResponseDto> RetrievePaymentMethodAsync(string id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieve Payment Method
        /// </summary>
        /// <remarks>
        /// Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </remarks>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentMethodResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaymentMethodResponseDto>> RetrievePaymentMethodWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPaymentMethodsApi : IPaymentMethodsApiSync, IPaymentMethodsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PaymentMethodsApi : IDisposable, IPaymentMethodsApi
    {
        private Cashful.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PaymentMethodsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PaymentMethodsApi(string basePath)
        {
            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                new Cashful.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PaymentMethodsApi(Cashful.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                new Cashful.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PaymentMethodsApi(HttpClient client, Cashful.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Client.Configuration.MergeConfigurations(
                Cashful.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PaymentMethodsApi(Cashful.Client.ISynchronousClient client, Cashful.Client.IAsynchronousClient asyncClient, Cashful.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cashful.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cashful.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cashful.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cashful.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cashful.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cashful.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete Payment Method Detaches and deletes a saved payment method from a customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>Object</returns>
        public Object DeletePaymentMethod(string id)
        {
            Cashful.Client.ApiResponse<Object> localVarResponse = DeletePaymentMethodWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Payment Method Detaches and deletes a saved payment method from a customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>ApiResponse of Object</returns>
        public Cashful.Client.ApiResponse<Object> DeletePaymentMethodWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'id' when calling PaymentMethodsApi->DeletePaymentMethod");

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Cashful.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/api/canary/payment-methods/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Payment Method Detaches and deletes a saved payment method from a customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeletePaymentMethodAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Client.ApiResponse<Object> localVarResponse = await DeletePaymentMethodWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Payment Method Detaches and deletes a saved payment method from a customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<Object>> DeletePaymentMethodWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'id' when calling PaymentMethodsApi->DeletePaymentMethod");


            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Cashful.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/api/canary/payment-methods/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeletePaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Payment Methods Lists saved payment methods for a specific customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <returns>ListPaymentMethodsResponseDto</returns>
        public ListPaymentMethodsResponseDto ListPaymentMethods(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default)
        {
            Cashful.Client.ApiResponse<ListPaymentMethodsResponseDto> localVarResponse = ListPaymentMethodsWithHttpInfo(merchantId, limit, offset, customerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Payment Methods Lists saved payment methods for a specific customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <returns>ApiResponse of ListPaymentMethodsResponseDto</returns>
        public Cashful.Client.ApiResponse<ListPaymentMethodsResponseDto> ListPaymentMethodsWithHttpInfo(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'merchantId' when calling PaymentMethodsApi->ListPaymentMethods");

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "merchantId", merchantId));
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "customerId", customerId));
            }

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListPaymentMethodsResponseDto>("/api/canary/payment-methods", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPaymentMethods", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Payment Methods Lists saved payment methods for a specific customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListPaymentMethodsResponseDto</returns>
        public async System.Threading.Tasks.Task<ListPaymentMethodsResponseDto> ListPaymentMethodsAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Client.ApiResponse<ListPaymentMethodsResponseDto> localVarResponse = await ListPaymentMethodsWithHttpInfoAsync(merchantId, limit, offset, customerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Payment Methods Lists saved payment methods for a specific customer.
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="merchantId">The unique identifier of the merchant</param>
        /// <param name="limit">Maximum number of records to return (optional)</param>
        /// <param name="offset">Number of records to skip (optional)</param>
        /// <param name="customerId">The unique identifier of the customer (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListPaymentMethodsResponseDto)</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<ListPaymentMethodsResponseDto>> ListPaymentMethodsWithHttpInfoAsync(string merchantId, decimal? limit = default, decimal? offset = default, string? customerId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'merchantId' is set
            if (merchantId == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'merchantId' when calling PaymentMethodsApi->ListPaymentMethods");


            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "merchantId", merchantId));
            if (customerId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Cashful.Client.ClientUtils.ParameterToMultiMap("", "customerId", customerId));
            }

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListPaymentMethodsResponseDto>("/api/canary/payment-methods", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPaymentMethods", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve Payment Method Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>PaymentMethodResponseDto</returns>
        public PaymentMethodResponseDto RetrievePaymentMethod(string id)
        {
            Cashful.Client.ApiResponse<PaymentMethodResponseDto> localVarResponse = RetrievePaymentMethodWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve Payment Method Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <returns>ApiResponse of PaymentMethodResponseDto</returns>
        public Cashful.Client.ApiResponse<PaymentMethodResponseDto> RetrievePaymentMethodWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'id' when calling PaymentMethodsApi->RetrievePaymentMethod");

            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Cashful.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PaymentMethodResponseDto>("/api/canary/payment-methods/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrievePaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve Payment Method Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaymentMethodResponseDto</returns>
        public async System.Threading.Tasks.Task<PaymentMethodResponseDto> RetrievePaymentMethodAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Client.ApiResponse<PaymentMethodResponseDto> localVarResponse = await RetrievePaymentMethodWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve Payment Method Gets the non-sensitive details of a saved card (e.g., brand, last 4).
        /// </summary>
        /// <exception cref="Cashful.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique identifier of the payment method</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaymentMethodResponseDto)</returns>
        public async System.Threading.Tasks.Task<Cashful.Client.ApiResponse<PaymentMethodResponseDto>> RetrievePaymentMethodWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Cashful.Client.ApiException(400, "Missing required parameter 'id' when calling PaymentMethodsApi->RetrievePaymentMethod");


            Cashful.Client.RequestOptions localVarRequestOptions = new Cashful.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Cashful.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PaymentMethodResponseDto>("/api/canary/payment-methods/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RetrievePaymentMethod", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
