/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing AdminCreateUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminCreateUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminCreateUserDto
        //private AdminCreateUserDto instance;

        public AdminCreateUserDtoTests()
        {
            // TODO uncomment below to create an instance of AdminCreateUserDto
            //instance = new AdminCreateUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminCreateUserDto
        /// </summary>
        [Fact]
        public void AdminCreateUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminCreateUserDto
            //Assert.IsType<AdminCreateUserDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'EmailVerified'
        /// </summary>
        [Fact]
        public void EmailVerifiedTest()
        {
            // TODO unit test for the property 'EmailVerified'
        }
    }
}
