/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing AdminUpdateUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminUpdateUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminUpdateUserDto
        //private AdminUpdateUserDto instance;

        public AdminUpdateUserDtoTests()
        {
            // TODO uncomment below to create an instance of AdminUpdateUserDto
            //instance = new AdminUpdateUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminUpdateUserDto
        /// </summary>
        [Fact]
        public void AdminUpdateUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminUpdateUserDto
            //Assert.IsType<AdminUpdateUserDto>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
