/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing AdminUpdateUserResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminUpdateUserResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminUpdateUserResponseDto
        //private AdminUpdateUserResponseDto instance;

        public AdminUpdateUserResponseDtoTests()
        {
            // TODO uncomment below to create an instance of AdminUpdateUserResponseDto
            //instance = new AdminUpdateUserResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminUpdateUserResponseDto
        /// </summary>
        [Fact]
        public void AdminUpdateUserResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminUpdateUserResponseDto
            //Assert.IsType<AdminUpdateUserResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
