/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing BanUserResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BanUserResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BanUserResponseDto
        //private BanUserResponseDto instance;

        public BanUserResponseDtoTests()
        {
            // TODO uncomment below to create an instance of BanUserResponseDto
            //instance = new BanUserResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BanUserResponseDto
        /// </summary>
        [Fact]
        public void BanUserResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BanUserResponseDto
            //Assert.IsType<BanUserResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
