/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing BanUserDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BanUserDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BanUserDto
        //private BanUserDto instance;

        public BanUserDtoTests()
        {
            // TODO uncomment below to create an instance of BanUserDto
            //instance = new BanUserDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BanUserDto
        /// </summary>
        [Fact]
        public void BanUserDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BanUserDto
            //Assert.IsType<BanUserDto>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'BanReason'
        /// </summary>
        [Fact]
        public void BanReasonTest()
        {
            // TODO unit test for the property 'BanReason'
        }

        /// <summary>
        /// Test the property 'BanExpiresIn'
        /// </summary>
        [Fact]
        public void BanExpiresInTest()
        {
            // TODO unit test for the property 'BanExpiresIn'
        }
    }
}
