/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ChangePasswordDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangePasswordDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangePasswordDto
        //private ChangePasswordDto instance;

        public ChangePasswordDtoTests()
        {
            // TODO uncomment below to create an instance of ChangePasswordDto
            //instance = new ChangePasswordDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangePasswordDto
        /// </summary>
        [Fact]
        public void ChangePasswordDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangePasswordDto
            //Assert.IsType<ChangePasswordDto>(instance);
        }

        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Fact]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }

        /// <summary>
        /// Test the property 'CurrentPassword'
        /// </summary>
        [Fact]
        public void CurrentPasswordTest()
        {
            // TODO unit test for the property 'CurrentPassword'
        }

        /// <summary>
        /// Test the property 'RevokeOtherSessions'
        /// </summary>
        [Fact]
        public void RevokeOtherSessionsTest()
        {
            // TODO unit test for the property 'RevokeOtherSessions'
        }
    }
}
