/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing CreateEventDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateEventDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateEventDto
        //private CreateEventDto instance;

        public CreateEventDtoTests()
        {
            // TODO uncomment below to create an instance of CreateEventDto
            //instance = new CreateEventDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateEventDto
        /// </summary>
        [Fact]
        public void CreateEventDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateEventDto
            //Assert.IsType<CreateEventDto>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'RelatedEntityId'
        /// </summary>
        [Fact]
        public void RelatedEntityIdTest()
        {
            // TODO unit test for the property 'RelatedEntityId'
        }

        /// <summary>
        /// Test the property 'RelatedEntityType'
        /// </summary>
        [Fact]
        public void RelatedEntityTypeTest()
        {
            // TODO unit test for the property 'RelatedEntityType'
        }
    }
}
