/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing CreatePaymentMethodDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreatePaymentMethodDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreatePaymentMethodDto
        //private CreatePaymentMethodDto instance;

        public CreatePaymentMethodDtoTests()
        {
            // TODO uncomment below to create an instance of CreatePaymentMethodDto
            //instance = new CreatePaymentMethodDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreatePaymentMethodDto
        /// </summary>
        [Fact]
        public void CreatePaymentMethodDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreatePaymentMethodDto
            //Assert.IsType<CreatePaymentMethodDto>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'CardNumber'
        /// </summary>
        [Fact]
        public void CardNumberTest()
        {
            // TODO unit test for the property 'CardNumber'
        }

        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }

        /// <summary>
        /// Test the property 'Last4'
        /// </summary>
        [Fact]
        public void Last4Test()
        {
            // TODO unit test for the property 'Last4'
        }

        /// <summary>
        /// Test the property 'ExpiryMonth'
        /// </summary>
        [Fact]
        public void ExpiryMonthTest()
        {
            // TODO unit test for the property 'ExpiryMonth'
        }

        /// <summary>
        /// Test the property 'ExpiryYear'
        /// </summary>
        [Fact]
        public void ExpiryYearTest()
        {
            // TODO unit test for the property 'ExpiryYear'
        }
    }
}
