/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteApiKeyResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteApiKeyResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteApiKeyResponseDto
        //private DeleteApiKeyResponseDto instance;

        public DeleteApiKeyResponseDtoTests()
        {
            // TODO uncomment below to create an instance of DeleteApiKeyResponseDto
            //instance = new DeleteApiKeyResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteApiKeyResponseDto
        /// </summary>
        [Fact]
        public void DeleteApiKeyResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteApiKeyResponseDto
            //Assert.IsType<DeleteApiKeyResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
