/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ForgotPasswordDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForgotPasswordDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ForgotPasswordDto
        //private ForgotPasswordDto instance;

        public ForgotPasswordDtoTests()
        {
            // TODO uncomment below to create an instance of ForgotPasswordDto
            //instance = new ForgotPasswordDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ForgotPasswordDto
        /// </summary>
        [Fact]
        public void ForgotPasswordDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ForgotPasswordDto
            //Assert.IsType<ForgotPasswordDto>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
