/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing HostedCheckoutConfigDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HostedCheckoutConfigDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HostedCheckoutConfigDto
        //private HostedCheckoutConfigDto instance;

        public HostedCheckoutConfigDtoTests()
        {
            // TODO uncomment below to create an instance of HostedCheckoutConfigDto
            //instance = new HostedCheckoutConfigDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HostedCheckoutConfigDto
        /// </summary>
        [Fact]
        public void HostedCheckoutConfigDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" HostedCheckoutConfigDto
            //Assert.IsType<HostedCheckoutConfigDto>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'MerchantAlias'
        /// </summary>
        [Fact]
        public void MerchantAliasTest()
        {
            // TODO unit test for the property 'MerchantAlias'
        }

        /// <summary>
        /// Test the property 'MerchantLegalName'
        /// </summary>
        [Fact]
        public void MerchantLegalNameTest()
        {
            // TODO unit test for the property 'MerchantLegalName'
        }

        /// <summary>
        /// Test the property 'MerchantAvatarTextPlaceholder'
        /// </summary>
        [Fact]
        public void MerchantAvatarTextPlaceholderTest()
        {
            // TODO unit test for the property 'MerchantAvatarTextPlaceholder'
        }

        /// <summary>
        /// Test the property 'MerchantAvatarUrl'
        /// </summary>
        [Fact]
        public void MerchantAvatarUrlTest()
        {
            // TODO unit test for the property 'MerchantAvatarUrl'
        }

        /// <summary>
        /// Test the property 'RequireContact'
        /// </summary>
        [Fact]
        public void RequireContactTest()
        {
            // TODO unit test for the property 'RequireContact'
        }

        /// <summary>
        /// Test the property 'RequireAddress'
        /// </summary>
        [Fact]
        public void RequireAddressTest()
        {
            // TODO unit test for the property 'RequireAddress'
        }

        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Fact]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }

        /// <summary>
        /// Test the property 'EmbedMode'
        /// </summary>
        [Fact]
        public void EmbedModeTest()
        {
            // TODO unit test for the property 'EmbedMode'
        }

        /// <summary>
        /// Test the property 'EmbedOrigin'
        /// </summary>
        [Fact]
        public void EmbedOriginTest()
        {
            // TODO unit test for the property 'EmbedOrigin'
        }
    }
}
