/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ImpersonateUserResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImpersonateUserResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImpersonateUserResponseDto
        //private ImpersonateUserResponseDto instance;

        public ImpersonateUserResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ImpersonateUserResponseDto
            //instance = new ImpersonateUserResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImpersonateUserResponseDto
        /// </summary>
        [Fact]
        public void ImpersonateUserResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImpersonateUserResponseDto
            //Assert.IsType<ImpersonateUserResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
