/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing InitiatePaymentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitiatePaymentDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitiatePaymentDto
        //private InitiatePaymentDto instance;

        public InitiatePaymentDtoTests()
        {
            // TODO uncomment below to create an instance of InitiatePaymentDto
            //instance = new InitiatePaymentDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitiatePaymentDto
        /// </summary>
        [Fact]
        public void InitiatePaymentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitiatePaymentDto
            //Assert.IsType<InitiatePaymentDto>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'EvervaultEncryptedCard'
        /// </summary>
        [Fact]
        public void EvervaultEncryptedCardTest()
        {
            // TODO unit test for the property 'EvervaultEncryptedCard'
        }

        /// <summary>
        /// Test the property 'PaymentIntentId'
        /// </summary>
        [Fact]
        public void PaymentIntentIdTest()
        {
            // TODO unit test for the property 'PaymentIntentId'
        }

        /// <summary>
        /// Test the property 'MaskedPan'
        /// </summary>
        [Fact]
        public void MaskedPanTest()
        {
            // TODO unit test for the property 'MaskedPan'
        }

        /// <summary>
        /// Test the property 'TokenizeCard'
        /// </summary>
        [Fact]
        public void TokenizeCardTest()
        {
            // TODO unit test for the property 'TokenizeCard'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'PaymentDescription'
        /// </summary>
        [Fact]
        public void PaymentDescriptionTest()
        {
            // TODO unit test for the property 'PaymentDescription'
        }

        /// <summary>
        /// Test the property 'MerchantName'
        /// </summary>
        [Fact]
        public void MerchantNameTest()
        {
            // TODO unit test for the property 'MerchantName'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
