/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing JwkDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JwkDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JwkDto
        //private JwkDto instance;

        public JwkDtoTests()
        {
            // TODO uncomment below to create an instance of JwkDto
            //instance = new JwkDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JwkDto
        /// </summary>
        [Fact]
        public void JwkDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" JwkDto
            //Assert.IsType<JwkDto>(instance);
        }

        /// <summary>
        /// Test the property 'Kid'
        /// </summary>
        [Fact]
        public void KidTest()
        {
            // TODO unit test for the property 'Kid'
        }

        /// <summary>
        /// Test the property 'Kty'
        /// </summary>
        [Fact]
        public void KtyTest()
        {
            // TODO unit test for the property 'Kty'
        }

        /// <summary>
        /// Test the property 'Alg'
        /// </summary>
        [Fact]
        public void AlgTest()
        {
            // TODO unit test for the property 'Alg'
        }

        /// <summary>
        /// Test the property 'Use'
        /// </summary>
        [Fact]
        public void UseTest()
        {
            // TODO unit test for the property 'Use'
        }

        /// <summary>
        /// Test the property 'N'
        /// </summary>
        [Fact]
        public void NTest()
        {
            // TODO unit test for the property 'N'
        }

        /// <summary>
        /// Test the property 'E'
        /// </summary>
        [Fact]
        public void ETest()
        {
            // TODO unit test for the property 'E'
        }

        /// <summary>
        /// Test the property 'Crv'
        /// </summary>
        [Fact]
        public void CrvTest()
        {
            // TODO unit test for the property 'Crv'
        }

        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Fact]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }

        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Fact]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
    }
}
