/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ListUsersResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListUsersResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListUsersResponseDto
        //private ListUsersResponseDto instance;

        public ListUsersResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ListUsersResponseDto
            //instance = new ListUsersResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListUsersResponseDto
        /// </summary>
        [Fact]
        public void ListUsersResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListUsersResponseDto
            //Assert.IsType<ListUsersResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
    }
}
