/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ListCustomerPaymentMethodsResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCustomerPaymentMethodsResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCustomerPaymentMethodsResponseDto
        //private ListCustomerPaymentMethodsResponseDto instance;

        public ListCustomerPaymentMethodsResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ListCustomerPaymentMethodsResponseDto
            //instance = new ListCustomerPaymentMethodsResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCustomerPaymentMethodsResponseDto
        /// </summary>
        [Fact]
        public void ListCustomerPaymentMethodsResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCustomerPaymentMethodsResponseDto
            //Assert.IsType<ListCustomerPaymentMethodsResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
