/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing NotFoundResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotFoundResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotFoundResponseDto
        //private NotFoundResponseDto instance;

        public NotFoundResponseDtoTests()
        {
            // TODO uncomment below to create an instance of NotFoundResponseDto
            //instance = new NotFoundResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotFoundResponseDto
        /// </summary>
        [Fact]
        public void NotFoundResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotFoundResponseDto
            //Assert.IsType<NotFoundResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
