/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing RequestPasswordResetResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestPasswordResetResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestPasswordResetResponseDto
        //private RequestPasswordResetResponseDto instance;

        public RequestPasswordResetResponseDtoTests()
        {
            // TODO uncomment below to create an instance of RequestPasswordResetResponseDto
            //instance = new RequestPasswordResetResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestPasswordResetResponseDto
        /// </summary>
        [Fact]
        public void RequestPasswordResetResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestPasswordResetResponseDto
            //Assert.IsType<RequestPasswordResetResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
