/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing ResetPasswordCallbackResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResetPasswordCallbackResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResetPasswordCallbackResponseDto
        //private ResetPasswordCallbackResponseDto instance;

        public ResetPasswordCallbackResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ResetPasswordCallbackResponseDto
            //instance = new ResetPasswordCallbackResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResetPasswordCallbackResponseDto
        /// </summary>
        [Fact]
        public void ResetPasswordCallbackResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResetPasswordCallbackResponseDto
            //Assert.IsType<ResetPasswordCallbackResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
    }
}
