/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing RevokeSessionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RevokeSessionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RevokeSessionDto
        //private RevokeSessionDto instance;

        public RevokeSessionDtoTests()
        {
            // TODO uncomment below to create an instance of RevokeSessionDto
            //instance = new RevokeSessionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RevokeSessionDto
        /// </summary>
        [Fact]
        public void RevokeSessionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RevokeSessionDto
            //Assert.IsType<RevokeSessionDto>(instance);
        }

        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
    }
}
