/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing SendEmail200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendEmail200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendEmail200Response
        //private SendEmail200Response instance;

        public SendEmail200ResponseTests()
        {
            // TODO uncomment below to create an instance of SendEmail200Response
            //instance = new SendEmail200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendEmail200Response
        /// </summary>
        [Fact]
        public void SendEmail200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendEmail200Response
            //Assert.IsType<SendEmail200Response>(instance);
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
    }
}
