/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing SetActiveOrganizationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetActiveOrganizationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetActiveOrganizationDto
        //private SetActiveOrganizationDto instance;

        public SetActiveOrganizationDtoTests()
        {
            // TODO uncomment below to create an instance of SetActiveOrganizationDto
            //instance = new SetActiveOrganizationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetActiveOrganizationDto
        /// </summary>
        [Fact]
        public void SetActiveOrganizationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetActiveOrganizationDto
            //Assert.IsType<SetActiveOrganizationDto>(instance);
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
    }
}
