/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing UnauthorizedResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnauthorizedResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnauthorizedResponseDto
        //private UnauthorizedResponseDto instance;

        public UnauthorizedResponseDtoTests()
        {
            // TODO uncomment below to create an instance of UnauthorizedResponseDto
            //instance = new UnauthorizedResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnauthorizedResponseDto
        /// </summary>
        [Fact]
        public void UnauthorizedResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnauthorizedResponseDto
            //Assert.IsType<UnauthorizedResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
