/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateApiKeyResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateApiKeyResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateApiKeyResponseDto
        //private UpdateApiKeyResponseDto instance;

        public UpdateApiKeyResponseDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateApiKeyResponseDto
            //instance = new UpdateApiKeyResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateApiKeyResponseDto
        /// </summary>
        [Fact]
        public void UpdateApiKeyResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateApiKeyResponseDto
            //Assert.IsType<UpdateApiKeyResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Fact]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
    }
}
