/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Model;
using Cashful.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateOrganizationComplianceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateOrganizationComplianceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateOrganizationComplianceDto
        //private UpdateOrganizationComplianceDto instance;

        public UpdateOrganizationComplianceDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateOrganizationComplianceDto
            //instance = new UpdateOrganizationComplianceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateOrganizationComplianceDto
        /// </summary>
        [Fact]
        public void UpdateOrganizationComplianceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateOrganizationComplianceDto
            //Assert.IsType<UpdateOrganizationComplianceDto>(instance);
        }

        /// <summary>
        /// Test the property 'CompanyRegistrationName'
        /// </summary>
        [Fact]
        public void CompanyRegistrationNameTest()
        {
            // TODO unit test for the property 'CompanyRegistrationName'
        }

        /// <summary>
        /// Test the property 'CompanyRegistrationNumber'
        /// </summary>
        [Fact]
        public void CompanyRegistrationNumberTest()
        {
            // TODO unit test for the property 'CompanyRegistrationNumber'
        }

        /// <summary>
        /// Test the property 'CompanyTradingName'
        /// </summary>
        [Fact]
        public void CompanyTradingNameTest()
        {
            // TODO unit test for the property 'CompanyTradingName'
        }

        /// <summary>
        /// Test the property 'VatRegistrationNumber'
        /// </summary>
        [Fact]
        public void VatRegistrationNumberTest()
        {
            // TODO unit test for the property 'VatRegistrationNumber'
        }

        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Fact]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }

        /// <summary>
        /// Test the property 'SubIndustry'
        /// </summary>
        [Fact]
        public void SubIndustryTest()
        {
            // TODO unit test for the property 'SubIndustry'
        }

        /// <summary>
        /// Test the property 'EstimatedAnnualTurnover'
        /// </summary>
        [Fact]
        public void EstimatedAnnualTurnoverTest()
        {
            // TODO unit test for the property 'EstimatedAnnualTurnover'
        }

        /// <summary>
        /// Test the property 'BusinessDescription'
        /// </summary>
        [Fact]
        public void BusinessDescriptionTest()
        {
            // TODO unit test for the property 'BusinessDescription'
        }

        /// <summary>
        /// Test the property 'CompanyMobileMoneySettlementNumber'
        /// </summary>
        [Fact]
        public void CompanyMobileMoneySettlementNumberTest()
        {
            // TODO unit test for the property 'CompanyMobileMoneySettlementNumber'
        }

        /// <summary>
        /// Test the property 'CompanyEmail'
        /// </summary>
        [Fact]
        public void CompanyEmailTest()
        {
            // TODO unit test for the property 'CompanyEmail'
        }

        /// <summary>
        /// Test the property 'CompanyContactNumber'
        /// </summary>
        [Fact]
        public void CompanyContactNumberTest()
        {
            // TODO unit test for the property 'CompanyContactNumber'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'SocialMedia'
        /// </summary>
        [Fact]
        public void SocialMediaTest()
        {
            // TODO unit test for the property 'SocialMedia'
        }

        /// <summary>
        /// Test the property 'AccountContactNumber'
        /// </summary>
        [Fact]
        public void AccountContactNumberTest()
        {
            // TODO unit test for the property 'AccountContactNumber'
        }

        /// <summary>
        /// Test the property 'CustomerSupportContactNumber'
        /// </summary>
        [Fact]
        public void CustomerSupportContactNumberTest()
        {
            // TODO unit test for the property 'CustomerSupportContactNumber'
        }

        /// <summary>
        /// Test the property 'CustomerSupportEscalationContactNumber'
        /// </summary>
        [Fact]
        public void CustomerSupportEscalationContactNumberTest()
        {
            // TODO unit test for the property 'CustomerSupportEscalationContactNumber'
        }

        /// <summary>
        /// Test the property 'EmergencyContactNumber'
        /// </summary>
        [Fact]
        public void EmergencyContactNumberTest()
        {
            // TODO unit test for the property 'EmergencyContactNumber'
        }

        /// <summary>
        /// Test the property 'StreetAddress'
        /// </summary>
        [Fact]
        public void StreetAddressTest()
        {
            // TODO unit test for the property 'StreetAddress'
        }

        /// <summary>
        /// Test the property 'Apartment'
        /// </summary>
        [Fact]
        public void ApartmentTest()
        {
            // TODO unit test for the property 'Apartment'
        }

        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Fact]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Fact]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Fact]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }

        /// <summary>
        /// Test the property 'BranchCode'
        /// </summary>
        [Fact]
        public void BranchCodeTest()
        {
            // TODO unit test for the property 'BranchCode'
        }

        /// <summary>
        /// Test the property 'SwiftCode'
        /// </summary>
        [Fact]
        public void SwiftCodeTest()
        {
            // TODO unit test for the property 'SwiftCode'
        }

        /// <summary>
        /// Test the property 'CertificateOfIncorporation'
        /// </summary>
        [Fact]
        public void CertificateOfIncorporationTest()
        {
            // TODO unit test for the property 'CertificateOfIncorporation'
        }

        /// <summary>
        /// Test the property 'IdentityDocuments'
        /// </summary>
        [Fact]
        public void IdentityDocumentsTest()
        {
            // TODO unit test for the property 'IdentityDocuments'
        }

        /// <summary>
        /// Test the property 'BankAccountConfirmationLetter'
        /// </summary>
        [Fact]
        public void BankAccountConfirmationLetterTest()
        {
            // TODO unit test for the property 'BankAccountConfirmationLetter'
        }

        /// <summary>
        /// Test the property 'ProofOfBusinessAddress'
        /// </summary>
        [Fact]
        public void ProofOfBusinessAddressTest()
        {
            // TODO unit test for the property 'ProofOfBusinessAddress'
        }

        /// <summary>
        /// Test the property 'TermsAccepted'
        /// </summary>
        [Fact]
        public void TermsAcceptedTest()
        {
            // TODO unit test for the property 'TermsAccepted'
        }

        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Fact]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }

        /// <summary>
        /// Test the property 'CurrentStep'
        /// </summary>
        [Fact]
        public void CurrentStepTest()
        {
            // TODO unit test for the property 'CurrentStep'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'IsCompleted'
        /// </summary>
        [Fact]
        public void IsCompletedTest()
        {
            // TODO unit test for the property 'IsCompleted'
        }

        /// <summary>
        /// Test the property 'CompletionScore'
        /// </summary>
        [Fact]
        public void CompletionScoreTest()
        {
            // TODO unit test for the property 'CompletionScore'
        }
    }
}
