/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cashful.Sdk.Client;
using Cashful.Sdk.Model;

namespace Cashful.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPurchasesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Buy with Cash Balance
        /// </summary>
        /// <remarks>
        /// (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </remarks>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <returns>PurchaseResponseDto</returns>
        PurchaseResponseDto CreatePurchase(CreatePurchaseDto createPurchaseDto);

        /// <summary>
        /// Buy with Cash Balance
        /// </summary>
        /// <remarks>
        /// (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </remarks>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <returns>ApiResponse of PurchaseResponseDto</returns>
        ApiResponse<PurchaseResponseDto> CreatePurchaseWithHttpInfo(CreatePurchaseDto createPurchaseDto);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPurchasesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Buy with Cash Balance
        /// </summary>
        /// <remarks>
        /// (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </remarks>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseResponseDto</returns>
        System.Threading.Tasks.Task<PurchaseResponseDto> CreatePurchaseAsync(CreatePurchaseDto createPurchaseDto, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Buy with Cash Balance
        /// </summary>
        /// <remarks>
        /// (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </remarks>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<PurchaseResponseDto>> CreatePurchaseWithHttpInfoAsync(CreatePurchaseDto createPurchaseDto, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPurchasesApi : IPurchasesApiSync, IPurchasesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PurchasesApi : IDisposable, IPurchasesApi
    {
        private Cashful.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PurchasesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PurchasesApi(string basePath)
        {
            this.Configuration = Cashful.Sdk.Client.Configuration.MergeConfigurations(
                Cashful.Sdk.Client.GlobalConfiguration.Instance,
                new Cashful.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PurchasesApi(Cashful.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cashful.Sdk.Client.Configuration.MergeConfigurations(
                Cashful.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PurchasesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PurchasesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Sdk.Client.Configuration.MergeConfigurations(
                Cashful.Sdk.Client.GlobalConfiguration.Instance,
                new Cashful.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cashful.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cashful.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PurchasesApi(HttpClient client, Cashful.Sdk.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cashful.Sdk.Client.Configuration.MergeConfigurations(
                Cashful.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cashful.Sdk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cashful.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PurchasesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PurchasesApi(Cashful.Sdk.Client.ISynchronousClient client, Cashful.Sdk.Client.IAsynchronousClient asyncClient, Cashful.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cashful.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cashful.Sdk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cashful.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cashful.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cashful.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cashful.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Buy with Cash Balance (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </summary>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <returns>PurchaseResponseDto</returns>
        public PurchaseResponseDto CreatePurchase(CreatePurchaseDto createPurchaseDto)
        {
            Cashful.Sdk.Client.ApiResponse<PurchaseResponseDto> localVarResponse = CreatePurchaseWithHttpInfo(createPurchaseDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Buy with Cash Balance (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </summary>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <returns>ApiResponse of PurchaseResponseDto</returns>
        public Cashful.Sdk.Client.ApiResponse<PurchaseResponseDto> CreatePurchaseWithHttpInfo(CreatePurchaseDto createPurchaseDto)
        {
            // verify the required parameter 'createPurchaseDto' is set
            if (createPurchaseDto == null)
                throw new Cashful.Sdk.Client.ApiException(400, "Missing required parameter 'createPurchaseDto' when calling PurchasesApi->CreatePurchase");

            Cashful.Sdk.Client.RequestOptions localVarRequestOptions = new Cashful.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Cashful.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createPurchaseDto;

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PurchaseResponseDto>("/api/canary/purchases", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Buy with Cash Balance (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </summary>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseResponseDto</returns>
        public async System.Threading.Tasks.Task<PurchaseResponseDto> CreatePurchaseAsync(CreatePurchaseDto createPurchaseDto, System.Threading.CancellationToken cancellationToken = default)
        {
            Cashful.Sdk.Client.ApiResponse<PurchaseResponseDto> localVarResponse = await CreatePurchaseWithHttpInfoAsync(createPurchaseDto, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Buy with Cash Balance (Wallet-Enabling) Spends a product using the CustomerBalance as the source. Atomically debits the CustomerBalance and credits the MerchantBalance.
        /// </summary>
        /// <exception cref="Cashful.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createPurchaseDto">Purchase details</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseResponseDto)</returns>
        public async System.Threading.Tasks.Task<Cashful.Sdk.Client.ApiResponse<PurchaseResponseDto>> CreatePurchaseWithHttpInfoAsync(CreatePurchaseDto createPurchaseDto, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createPurchaseDto' is set
            if (createPurchaseDto == null)
                throw new Cashful.Sdk.Client.ApiException(400, "Missing required parameter 'createPurchaseDto' when calling PurchasesApi->CreatePurchase");


            Cashful.Sdk.Client.RequestOptions localVarRequestOptions = new Cashful.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Cashful.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cashful.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createPurchaseDto;

            // authentication (bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PurchaseResponseDto>("/api/canary/purchases", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePurchase", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
