/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cashful.Client;
using Cashful.Api;
// uncomment below to import models
//using Cashful.Model;

namespace Cashful.Test.Api
{
    /// <summary>
    ///  Class for testing CheckoutsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CheckoutsApiTests : IDisposable
    {
        private CheckoutsApi instance;

        public CheckoutsApiTests()
        {
            instance = new CheckoutsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CheckoutsApi
            //Assert.IsType<CheckoutsApi>(instance);
        }

        /// <summary>
        /// Test CreateCheckoutSession
        /// </summary>
        [Fact]
        public void CreateCheckoutSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCheckoutSessionDto createCheckoutSessionDto = null;
            //var response = instance.CreateCheckoutSession(createCheckoutSessionDto);
            //Assert.IsType<CheckoutSessionResponseDto>(response);
        }

        /// <summary>
        /// Test ListCheckoutSessions
        /// </summary>
        [Fact]
        public void ListCheckoutSessionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal? limit = null;
            //decimal? offset = null;
            //var response = instance.ListCheckoutSessions(limit, offset);
            //Assert.IsType<ListCheckoutSessionsResponseDto>(response);
        }

        /// <summary>
        /// Test RetrieveCheckoutSession
        /// </summary>
        [Fact]
        public void RetrieveCheckoutSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RetrieveCheckoutSession(id);
            //Assert.IsType<CheckoutSessionResponseDto>(response);
        }
    }
}
