/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cashful.Client;
using Cashful.Api;
// uncomment below to import models
//using Cashful.Model;

namespace Cashful.Test.Api
{
    /// <summary>
    ///  Class for testing NotificationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NotificationsApiTests : IDisposable
    {
        private NotificationsApi instance;

        public NotificationsApiTests()
        {
            instance = new NotificationsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NotificationsApi
            //Assert.IsType<NotificationsApi>(instance);
        }

        /// <summary>
        /// Test SendEmail
        /// </summary>
        [Fact]
        public void SendEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendEmailDto sendEmailDto = null;
            //var response = instance.SendEmail(sendEmailDto);
            //Assert.IsType<SendEmail200Response>(response);
        }

        /// <summary>
        /// Test SendMultiChannelNotification
        /// </summary>
        [Fact]
        public void SendMultiChannelNotificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SendMultiChannelNotification();
            //Assert.IsType<SendMultiChannelNotification200Response>(response);
        }

        /// <summary>
        /// Test SendNotification
        /// </summary>
        [Fact]
        public void SendNotificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificationDto notificationDto = null;
            //instance.SendNotification(notificationDto);
        }

        /// <summary>
        /// Test SendSms
        /// </summary>
        [Fact]
        public void SendSmsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendSmsDto sendSmsDto = null;
            //var response = instance.SendSms(sendSmsDto);
            //Assert.IsType<SendSms200Response>(response);
        }
    }
}
