/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cashful.Client;
using Cashful.Api;
// uncomment below to import models
//using Cashful.Model;

namespace Cashful.Test.Api
{
    /// <summary>
    ///  Class for testing PayoutsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PayoutsApiTests : IDisposable
    {
        private PayoutsApi instance;

        public PayoutsApiTests()
        {
            instance = new PayoutsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayoutsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PayoutsApi
            //Assert.IsType<PayoutsApi>(instance);
        }

        /// <summary>
        /// Test CreatePayout
        /// </summary>
        [Fact]
        public void CreatePayoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePayoutDto createPayoutDto = null;
            //var response = instance.CreatePayout(createPayoutDto);
            //Assert.IsType<PayoutResponseDto>(response);
        }

        /// <summary>
        /// Test ListPayouts
        /// </summary>
        [Fact]
        public void ListPayoutsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? merchantId = null;
            //decimal? limit = null;
            //decimal? offset = null;
            //string? status = null;
            //var response = instance.ListPayouts(merchantId, limit, offset, status);
            //Assert.IsType<ListPayoutsResponseDto>(response);
        }
    }
}
