/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AdminRevokeUserSessionsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminRevokeUserSessionsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminRevokeUserSessionsDto
        //private AdminRevokeUserSessionsDto instance;

        public AdminRevokeUserSessionsDtoTests()
        {
            // TODO uncomment below to create an instance of AdminRevokeUserSessionsDto
            //instance = new AdminRevokeUserSessionsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminRevokeUserSessionsDto
        /// </summary>
        [Fact]
        public void AdminRevokeUserSessionsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminRevokeUserSessionsDto
            //Assert.IsType<AdminRevokeUserSessionsDto>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
