/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsSummaryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsSummaryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsSummaryDto
        //private AnalyticsSummaryDto instance;

        public AnalyticsSummaryDtoTests()
        {
            // TODO uncomment below to create an instance of AnalyticsSummaryDto
            //instance = new AnalyticsSummaryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsSummaryDto
        /// </summary>
        [Fact]
        public void AnalyticsSummaryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsSummaryDto
            //Assert.IsType<AnalyticsSummaryDto>(instance);
        }

        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }

        /// <summary>
        /// Test the property 'Customers'
        /// </summary>
        [Fact]
        public void CustomersTest()
        {
            // TODO unit test for the property 'Customers'
        }

        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

        /// <summary>
        /// Test the property 'Members'
        /// </summary>
        [Fact]
        public void MembersTest()
        {
            // TODO unit test for the property 'Members'
        }
    }
}
