/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateApiKeyResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateApiKeyResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateApiKeyResponseDto
        //private CreateApiKeyResponseDto instance;

        public CreateApiKeyResponseDtoTests()
        {
            // TODO uncomment below to create an instance of CreateApiKeyResponseDto
            //instance = new CreateApiKeyResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateApiKeyResponseDto
        /// </summary>
        [Fact]
        public void CreateApiKeyResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateApiKeyResponseDto
            //Assert.IsType<CreateApiKeyResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Fact]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
    }
}
