/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteUserResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteUserResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteUserResponseDto
        //private DeleteUserResponseDto instance;

        public DeleteUserResponseDtoTests()
        {
            // TODO uncomment below to create an instance of DeleteUserResponseDto
            //instance = new DeleteUserResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteUserResponseDto
        /// </summary>
        [Fact]
        public void DeleteUserResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteUserResponseDto
            //Assert.IsType<DeleteUserResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
