/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListEventsResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListEventsResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListEventsResponseDto
        //private ListEventsResponseDto instance;

        public ListEventsResponseDtoTests()
        {
            // TODO uncomment below to create an instance of ListEventsResponseDto
            //instance = new ListEventsResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListEventsResponseDto
        /// </summary>
        [Fact]
        public void ListEventsResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListEventsResponseDto
            //Assert.IsType<ListEventsResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
