/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseResponseDto
        //private PurchaseResponseDto instance;

        public PurchaseResponseDtoTests()
        {
            // TODO uncomment below to create an instance of PurchaseResponseDto
            //instance = new PurchaseResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseResponseDto
        /// </summary>
        [Fact]
        public void PurchaseResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseResponseDto
            //Assert.IsType<PurchaseResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'MerchantId'
        /// </summary>
        [Fact]
        public void MerchantIdTest()
        {
            // TODO unit test for the property 'MerchantId'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CustomerBalanceBefore'
        /// </summary>
        [Fact]
        public void CustomerBalanceBeforeTest()
        {
            // TODO unit test for the property 'CustomerBalanceBefore'
        }

        /// <summary>
        /// Test the property 'CustomerBalanceAfter'
        /// </summary>
        [Fact]
        public void CustomerBalanceAfterTest()
        {
            // TODO unit test for the property 'CustomerBalanceAfter'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
