/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RejectInvitationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RejectInvitationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RejectInvitationDto
        //private RejectInvitationDto instance;

        public RejectInvitationDtoTests()
        {
            // TODO uncomment below to create an instance of RejectInvitationDto
            //instance = new RejectInvitationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RejectInvitationDto
        /// </summary>
        [Fact]
        public void RejectInvitationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RejectInvitationDto
            //Assert.IsType<RejectInvitationDto>(instance);
        }

        /// <summary>
        /// Test the property 'InvitationId'
        /// </summary>
        [Fact]
        public void InvitationIdTest()
        {
            // TODO unit test for the property 'InvitationId'
        }
    }
}
