/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RequestPasswordResetDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestPasswordResetDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestPasswordResetDto
        //private RequestPasswordResetDto instance;

        public RequestPasswordResetDtoTests()
        {
            // TODO uncomment below to create an instance of RequestPasswordResetDto
            //instance = new RequestPasswordResetDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestPasswordResetDto
        /// </summary>
        [Fact]
        public void RequestPasswordResetDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestPasswordResetDto
            //Assert.IsType<RequestPasswordResetDto>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'RedirectTo'
        /// </summary>
        [Fact]
        public void RedirectToTest()
        {
            // TODO unit test for the property 'RedirectTo'
        }
    }
}
