/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SignInPhoneNumberDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignInPhoneNumberDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignInPhoneNumberDto
        //private SignInPhoneNumberDto instance;

        public SignInPhoneNumberDtoTests()
        {
            // TODO uncomment below to create an instance of SignInPhoneNumberDto
            //instance = new SignInPhoneNumberDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignInPhoneNumberDto
        /// </summary>
        [Fact]
        public void SignInPhoneNumberDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignInPhoneNumberDto
            //Assert.IsType<SignInPhoneNumberDto>(instance);
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'CallbackURL'
        /// </summary>
        [Fact]
        public void CallbackURLTest()
        {
            // TODO unit test for the property 'CallbackURL'
        }
    }
}
