/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyApiKeyResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyApiKeyResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyApiKeyResponseDto
        //private VerifyApiKeyResponseDto instance;

        public VerifyApiKeyResponseDtoTests()
        {
            // TODO uncomment below to create an instance of VerifyApiKeyResponseDto
            //instance = new VerifyApiKeyResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyApiKeyResponseDto
        /// </summary>
        [Fact]
        public void VerifyApiKeyResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyApiKeyResponseDto
            //Assert.IsType<VerifyApiKeyResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
    }
}
