/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cashful.Sdk.Model;
using Cashful.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cashful.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyEmailResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyEmailResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyEmailResponseDto
        //private VerifyEmailResponseDto instance;

        public VerifyEmailResponseDtoTests()
        {
            // TODO uncomment below to create an instance of VerifyEmailResponseDto
            //instance = new VerifyEmailResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyEmailResponseDto
        /// </summary>
        [Fact]
        public void VerifyEmailResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyEmailResponseDto
            //Assert.IsType<VerifyEmailResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
