/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// BalanceTransactionDto
    /// </summary>
    [DataContract(Name = "BalanceTransactionDto")]
    public partial class BalanceTransactionDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceTransactionDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BalanceTransactionDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceTransactionDto" /> class.
        /// </summary>
        /// <param name="id">Unique identifier (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="deletedAt">deletedAt.</param>
        /// <param name="merchantId">merchantId.</param>
        /// <param name="type">type (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="relatedEntityId">relatedEntityId.</param>
        /// <param name="relatedEntityType">relatedEntityType.</param>
        /// <param name="balanceAfter">balanceAfter.</param>
        public BalanceTransactionDto(string id = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default, DateTimeOffset deletedAt = default, string merchantId = default, string type = default, decimal amount = default, string currency = default, string description = default, string relatedEntityId = default, string relatedEntityType = default, decimal balanceAfter = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for BalanceTransactionDto and cannot be null");
            }
            this.Id = id;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for BalanceTransactionDto and cannot be null");
            }
            this.Type = type;
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for BalanceTransactionDto and cannot be null");
            }
            this.Currency = currency;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for BalanceTransactionDto and cannot be null");
            }
            this.Description = description;
            this.DeletedAt = deletedAt;
            this.MerchantId = merchantId;
            this.RelatedEntityId = relatedEntityId;
            this.RelatedEntityType = relatedEntityType;
            this.BalanceAfter = balanceAfter;
        }

        /// <summary>
        /// Unique identifier
        /// </summary>
        /// <value>Unique identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets DeletedAt
        /// </summary>
        [DataMember(Name = "deletedAt", EmitDefaultValue = false)]
        public DateTimeOffset DeletedAt { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets RelatedEntityId
        /// </summary>
        [DataMember(Name = "relatedEntityId", EmitDefaultValue = false)]
        public string RelatedEntityId { get; set; }

        /// <summary>
        /// Gets or Sets RelatedEntityType
        /// </summary>
        [DataMember(Name = "relatedEntityType", EmitDefaultValue = false)]
        public string RelatedEntityType { get; set; }

        /// <summary>
        /// Gets or Sets BalanceAfter
        /// </summary>
        [DataMember(Name = "balanceAfter", EmitDefaultValue = false)]
        public decimal BalanceAfter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BalanceTransactionDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  DeletedAt: ").Append(DeletedAt).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  RelatedEntityId: ").Append(RelatedEntityId).Append("\n");
            sb.Append("  RelatedEntityType: ").Append(RelatedEntityType).Append("\n");
            sb.Append("  BalanceAfter: ").Append(BalanceAfter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
