/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// ConfirmPaymentIntentResponseDto
    /// </summary>
    [DataContract(Name = "ConfirmPaymentIntentResponseDto")]
    public partial class ConfirmPaymentIntentResponseDto : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            [EnumMember(Value = "succeeded")]
            Succeeded = 1,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 2
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmPaymentIntentResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfirmPaymentIntentResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfirmPaymentIntentResponseDto" /> class.
        /// </summary>
        /// <param name="paymentIntent">paymentIntent (required).</param>
        /// <param name="iveriParams">iveriParams.</param>
        /// <param name="iVeri3dsEndpoint">iVeri3dsEndpoint.</param>
        /// <param name="sandboxMode">sandboxMode.</param>
        /// <param name="status">status.</param>
        /// <param name="transactionId">transactionId.</param>
        /// <param name="authCode">authCode.</param>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="reason">reason.</param>
        public ConfirmPaymentIntentResponseDto(PaymentIntentResponseDto paymentIntent = default, Object iveriParams = default, string iVeri3dsEndpoint = default, bool sandboxMode = default, StatusEnum? status = default, string transactionId = default, string authCode = default, decimal amount = default, string currency = default, string reason = default)
        {
            // to ensure "paymentIntent" is required (not null)
            if (paymentIntent == null)
            {
                throw new ArgumentNullException("paymentIntent is a required property for ConfirmPaymentIntentResponseDto and cannot be null");
            }
            this.PaymentIntent = paymentIntent;
            this.IveriParams = iveriParams;
            this.IVeri3dsEndpoint = iVeri3dsEndpoint;
            this.SandboxMode = sandboxMode;
            this.Status = status;
            this.TransactionId = transactionId;
            this.AuthCode = authCode;
            this.Amount = amount;
            this.Currency = currency;
            this.Reason = reason;
        }

        /// <summary>
        /// Gets or Sets PaymentIntent
        /// </summary>
        [DataMember(Name = "paymentIntent", IsRequired = true, EmitDefaultValue = true)]
        public PaymentIntentResponseDto PaymentIntent { get; set; }

        /// <summary>
        /// Gets or Sets IveriParams
        /// </summary>
        [DataMember(Name = "iveriParams", EmitDefaultValue = false)]
        public Object IveriParams { get; set; }

        /// <summary>
        /// Gets or Sets IVeri3dsEndpoint
        /// </summary>
        [DataMember(Name = "iVeri3dsEndpoint", EmitDefaultValue = false)]
        public string IVeri3dsEndpoint { get; set; }

        /// <summary>
        /// Gets or Sets SandboxMode
        /// </summary>
        [DataMember(Name = "sandboxMode", EmitDefaultValue = true)]
        public bool SandboxMode { get; set; }

        /// <summary>
        /// Gets or Sets TransactionId
        /// </summary>
        [DataMember(Name = "transactionId", EmitDefaultValue = false)]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or Sets AuthCode
        /// </summary>
        [DataMember(Name = "authCode", EmitDefaultValue = false)]
        public string AuthCode { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfirmPaymentIntentResponseDto {\n");
            sb.Append("  PaymentIntent: ").Append(PaymentIntent).Append("\n");
            sb.Append("  IveriParams: ").Append(IveriParams).Append("\n");
            sb.Append("  IVeri3dsEndpoint: ").Append(IVeri3dsEndpoint).Append("\n");
            sb.Append("  SandboxMode: ").Append(SandboxMode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TransactionId: ").Append(TransactionId).Append("\n");
            sb.Append("  AuthCode: ").Append(AuthCode).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
