/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// CreatePaymentIntentDto
    /// </summary>
    [DataContract(Name = "CreatePaymentIntentDto")]
    public partial class CreatePaymentIntentDto : IValidatableObject
    {
        /// <summary>
        /// The mode of the payment intent
        /// </summary>
        /// <value>The mode of the payment intent</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModeEnum
        {
            /// <summary>
            /// Enum Payment for value: payment
            /// </summary>
            [EnumMember(Value = "payment")]
            Payment = 1,

            /// <summary>
            /// Enum Setup for value: setup
            /// </summary>
            [EnumMember(Value = "setup")]
            Setup = 2,

            /// <summary>
            /// Enum Subscription for value: subscription
            /// </summary>
            [EnumMember(Value = "subscription")]
            Subscription = 3
        }


        /// <summary>
        /// The mode of the payment intent
        /// </summary>
        /// <value>The mode of the payment intent</value>
        [DataMember(Name = "mode", EmitDefaultValue = false)]
        public ModeEnum? Mode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePaymentIntentDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreatePaymentIntentDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePaymentIntentDto" /> class.
        /// </summary>
        /// <param name="merchantId">The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant..</param>
        /// <param name="customerId">The unique identifier of the customer. Optional for payment intents that don&#39;t require a customer..</param>
        /// <param name="paymentMethodId">The unique identifier of the payment method. Optional if payment method will be collected later..</param>
        /// <param name="amount">The amount to charge in the smallest currency unit (cents) (required).</param>
        /// <param name="currency">The three-letter ISO 4217 currency code (required).</param>
        /// <param name="mode">The mode of the payment intent (default to ModeEnum.Payment).</param>
        /// <param name="description">Optional description for the payment.</param>
        /// <param name="metadata">Optional custom metadata.</param>
        /// <param name="idempotencyKey">A unique key to prevent duplicate charges. If not provided, one will be generated..</param>
        /// <param name="expiresAt">When the payment intent expires. Defaults to 24 hours from creation..</param>
        public CreatePaymentIntentDto(string merchantId = default, string customerId = default, string paymentMethodId = default, decimal amount = default, string currency = default, ModeEnum? mode = ModeEnum.Payment, string description = default, Dictionary<string, Object> metadata = default, string idempotencyKey = default, DateTimeOffset expiresAt = default)
        {
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CreatePaymentIntentDto and cannot be null");
            }
            this.Currency = currency;
            this.MerchantId = merchantId;
            this.CustomerId = customerId;
            this.PaymentMethodId = paymentMethodId;
            this.Mode = mode;
            this.Description = description;
            this.Metadata = metadata;
            this.IdempotencyKey = idempotencyKey;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.
        /// </summary>
        /// <value>The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.</value>
        [DataMember(Name = "merchantId", EmitDefaultValue = false)]
        public string MerchantId { get; set; }

        /// <summary>
        /// The unique identifier of the customer. Optional for payment intents that don&#39;t require a customer.
        /// </summary>
        /// <value>The unique identifier of the customer. Optional for payment intents that don&#39;t require a customer.</value>
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public string CustomerId { get; set; }

        /// <summary>
        /// The unique identifier of the payment method. Optional if payment method will be collected later.
        /// </summary>
        /// <value>The unique identifier of the payment method. Optional if payment method will be collected later.</value>
        [DataMember(Name = "paymentMethodId", EmitDefaultValue = false)]
        public string PaymentMethodId { get; set; }

        /// <summary>
        /// The amount to charge in the smallest currency unit (cents)
        /// </summary>
        /// <value>The amount to charge in the smallest currency unit (cents)</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// The three-letter ISO 4217 currency code
        /// </summary>
        /// <value>The three-letter ISO 4217 currency code</value>
        /*
        <example>ZAR</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Optional description for the payment
        /// </summary>
        /// <value>Optional description for the payment</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Optional custom metadata
        /// </summary>
        /// <value>Optional custom metadata</value>
        /*
        <example>{&quot;orderId&quot;:&quot;12345&quot;,&quot;customField&quot;:&quot;value&quot;}</example>
        */
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// A unique key to prevent duplicate charges. If not provided, one will be generated.
        /// </summary>
        /// <value>A unique key to prevent duplicate charges. If not provided, one will be generated.</value>
        [DataMember(Name = "idempotencyKey", EmitDefaultValue = false)]
        public string IdempotencyKey { get; set; }

        /// <summary>
        /// When the payment intent expires. Defaults to 24 hours from creation.
        /// </summary>
        /// <value>When the payment intent expires. Defaults to 24 hours from creation.</value>
        [DataMember(Name = "expiresAt", EmitDefaultValue = false)]
        public DateTimeOffset ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePaymentIntentDto {\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  PaymentMethodId: ").Append(PaymentMethodId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
