/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// DeleteApiKeyDto
    /// </summary>
    [DataContract(Name = "DeleteApiKeyDto")]
    public partial class DeleteApiKeyDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteApiKeyDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteApiKeyDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteApiKeyDto" /> class.
        /// </summary>
        /// <param name="keyId">The ID of the API key to delete (required).</param>
        public DeleteApiKeyDto(string keyId = default)
        {
            // to ensure "keyId" is required (not null)
            if (keyId == null)
            {
                throw new ArgumentNullException("keyId is a required property for DeleteApiKeyDto and cannot be null");
            }
            this.KeyId = keyId;
        }

        /// <summary>
        /// The ID of the API key to delete
        /// </summary>
        /// <value>The ID of the API key to delete</value>
        /*
        <example>key_12345</example>
        */
        [DataMember(Name = "keyId", IsRequired = true, EmitDefaultValue = true)]
        public string KeyId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteApiKeyDto {\n");
            sb.Append("  KeyId: ").Append(KeyId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
