/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// EventResponseDto
    /// </summary>
    [DataContract(Name = "EventResponseDto")]
    public partial class EventResponseDto : IValidatableObject
    {
        /// <summary>
        /// Current delivery status of the event
        /// </summary>
        /// <value>Current delivery status of the event</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Delivered for value: delivered
            /// </summary>
            [EnumMember(Value = "delivered")]
            Delivered = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 3
        }


        /// <summary>
        /// Current delivery status of the event
        /// </summary>
        /// <value>Current delivery status of the event</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventResponseDto" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the event (required).</param>
        /// <param name="merchantId">ID of the merchant this event belongs to (required).</param>
        /// <param name="webhookEndpointId">ID of the webhook endpoint this event was sent to (required).</param>
        /// <param name="type">Event type name (required).</param>
        /// <param name="data">Event data payload (required).</param>
        /// <param name="status">Current delivery status of the event (required).</param>
        /// <param name="attempts">Number of delivery attempts (required).</param>
        /// <param name="relatedEntityId">ID of the related entity.</param>
        /// <param name="relatedEntityType">Type of the related entity.</param>
        /// <param name="lastAttemptAt">Timestamp of the last delivery attempt.</param>
        /// <param name="nextRetryAt">Timestamp for the next retry attempt.</param>
        /// <param name="deliveredAt">Timestamp when the event was successfully delivered.</param>
        /// <param name="createdAt">Timestamp when the event was created (required).</param>
        /// <param name="updatedAt">Timestamp when the event was last updated (required).</param>
        public EventResponseDto(string id = default, string merchantId = default, string webhookEndpointId = default, string type = default, Object data = default, StatusEnum status = default, decimal attempts = default, string relatedEntityId = default, string relatedEntityType = default, DateTimeOffset lastAttemptAt = default, DateTimeOffset nextRetryAt = default, DateTimeOffset deliveredAt = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for EventResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantId" is required (not null)
            if (merchantId == null)
            {
                throw new ArgumentNullException("merchantId is a required property for EventResponseDto and cannot be null");
            }
            this.MerchantId = merchantId;
            // to ensure "webhookEndpointId" is required (not null)
            if (webhookEndpointId == null)
            {
                throw new ArgumentNullException("webhookEndpointId is a required property for EventResponseDto and cannot be null");
            }
            this.WebhookEndpointId = webhookEndpointId;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for EventResponseDto and cannot be null");
            }
            this.Type = type;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for EventResponseDto and cannot be null");
            }
            this.Data = data;
            this.Status = status;
            this.Attempts = attempts;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.RelatedEntityId = relatedEntityId;
            this.RelatedEntityType = relatedEntityType;
            this.LastAttemptAt = lastAttemptAt;
            this.NextRetryAt = nextRetryAt;
            this.DeliveredAt = deliveredAt;
        }

        /// <summary>
        /// Unique identifier for the event
        /// </summary>
        /// <value>Unique identifier for the event</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// ID of the merchant this event belongs to
        /// </summary>
        /// <value>ID of the merchant this event belongs to</value>
        [DataMember(Name = "merchantId", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantId { get; set; }

        /// <summary>
        /// ID of the webhook endpoint this event was sent to
        /// </summary>
        /// <value>ID of the webhook endpoint this event was sent to</value>
        [DataMember(Name = "webhookEndpointId", IsRequired = true, EmitDefaultValue = true)]
        public string WebhookEndpointId { get; set; }

        /// <summary>
        /// Event type name
        /// </summary>
        /// <value>Event type name</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Event data payload
        /// </summary>
        /// <value>Event data payload</value>
        /*
        <example>{&quot;key&quot;:&quot;value&quot;}</example>
        */
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public Object Data { get; set; }

        /// <summary>
        /// Number of delivery attempts
        /// </summary>
        /// <value>Number of delivery attempts</value>
        [DataMember(Name = "attempts", IsRequired = true, EmitDefaultValue = true)]
        public decimal Attempts { get; set; }

        /// <summary>
        /// ID of the related entity
        /// </summary>
        /// <value>ID of the related entity</value>
        [DataMember(Name = "relatedEntityId", EmitDefaultValue = false)]
        public string RelatedEntityId { get; set; }

        /// <summary>
        /// Type of the related entity
        /// </summary>
        /// <value>Type of the related entity</value>
        [DataMember(Name = "relatedEntityType", EmitDefaultValue = false)]
        public string RelatedEntityType { get; set; }

        /// <summary>
        /// Timestamp of the last delivery attempt
        /// </summary>
        /// <value>Timestamp of the last delivery attempt</value>
        [DataMember(Name = "lastAttemptAt", EmitDefaultValue = false)]
        public DateTimeOffset LastAttemptAt { get; set; }

        /// <summary>
        /// Timestamp for the next retry attempt
        /// </summary>
        /// <value>Timestamp for the next retry attempt</value>
        [DataMember(Name = "nextRetryAt", EmitDefaultValue = false)]
        public DateTimeOffset NextRetryAt { get; set; }

        /// <summary>
        /// Timestamp when the event was successfully delivered
        /// </summary>
        /// <value>Timestamp when the event was successfully delivered</value>
        [DataMember(Name = "deliveredAt", EmitDefaultValue = false)]
        public DateTimeOffset DeliveredAt { get; set; }

        /// <summary>
        /// Timestamp when the event was created
        /// </summary>
        /// <value>Timestamp when the event was created</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Timestamp when the event was last updated
        /// </summary>
        /// <value>Timestamp when the event was last updated</value>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  WebhookEndpointId: ").Append(WebhookEndpointId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Attempts: ").Append(Attempts).Append("\n");
            sb.Append("  RelatedEntityId: ").Append(RelatedEntityId).Append("\n");
            sb.Append("  RelatedEntityType: ").Append(RelatedEntityType).Append("\n");
            sb.Append("  LastAttemptAt: ").Append(LastAttemptAt).Append("\n");
            sb.Append("  NextRetryAt: ").Append(NextRetryAt).Append("\n");
            sb.Append("  DeliveredAt: ").Append(DeliveredAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
