/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// GetAccessTokenDto
    /// </summary>
    [DataContract(Name = "GetAccessTokenDto")]
    public partial class GetAccessTokenDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAccessTokenDto" /> class.
        /// </summary>
        /// <param name="provider">The provider to get token for.</param>
        /// <param name="forceRefresh">Whether to force token refresh.</param>
        public GetAccessTokenDto(string provider = default, bool forceRefresh = default)
        {
            this.Provider = provider;
            this.ForceRefresh = forceRefresh;
        }

        /// <summary>
        /// The provider to get token for
        /// </summary>
        /// <value>The provider to get token for</value>
        /*
        <example>google</example>
        */
        [DataMember(Name = "provider", EmitDefaultValue = false)]
        public string Provider { get; set; }

        /// <summary>
        /// Whether to force token refresh
        /// </summary>
        /// <value>Whether to force token refresh</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "forceRefresh", EmitDefaultValue = true)]
        public bool ForceRefresh { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAccessTokenDto {\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  ForceRefresh: ").Append(ForceRefresh).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
