/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// GetFullOrganizationResponseDto
    /// </summary>
    [DataContract(Name = "GetFullOrganizationResponseDto")]
    public partial class GetFullOrganizationResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFullOrganizationResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetFullOrganizationResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFullOrganizationResponseDto" /> class.
        /// </summary>
        /// <param name="organization">The full organization object (required).</param>
        public GetFullOrganizationResponseDto(OrganizationDto organization = default)
        {
            // to ensure "organization" is required (not null)
            if (organization == null)
            {
                throw new ArgumentNullException("organization is a required property for GetFullOrganizationResponseDto and cannot be null");
            }
            this.Organization = organization;
        }

        /// <summary>
        /// The full organization object
        /// </summary>
        /// <value>The full organization object</value>
        [DataMember(Name = "organization", IsRequired = true, EmitDefaultValue = true)]
        public OrganizationDto Organization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetFullOrganizationResponseDto {\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
