/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// InviteMemberResponseDto
    /// </summary>
    [DataContract(Name = "InviteMemberResponseDto")]
    public partial class InviteMemberResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteMemberResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InviteMemberResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InviteMemberResponseDto" /> class.
        /// </summary>
        /// <param name="invitation">Member invited successfully (required).</param>
        public InviteMemberResponseDto(Object invitation = default)
        {
            // to ensure "invitation" is required (not null)
            if (invitation == null)
            {
                throw new ArgumentNullException("invitation is a required property for InviteMemberResponseDto and cannot be null");
            }
            this.Invitation = invitation;
        }

        /// <summary>
        /// Member invited successfully
        /// </summary>
        /// <value>Member invited successfully</value>
        /*
        <example>{&quot;id&quot;:&quot;inv_123&quot;,&quot;email&quot;:&quot;member@example.com&quot;}</example>
        */
        [DataMember(Name = "invitation", IsRequired = true, EmitDefaultValue = true)]
        public Object Invitation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InviteMemberResponseDto {\n");
            sb.Append("  Invitation: ").Append(Invitation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
