/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// JwkDto
    /// </summary>
    [DataContract(Name = "JwkDto")]
    public partial class JwkDto : IValidatableObject
    {
        /// <summary>
        /// Intended use of the public key
        /// </summary>
        /// <value>Intended use of the public key</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UseEnum
        {
            /// <summary>
            /// Enum Sig for value: sig
            /// </summary>
            [EnumMember(Value = "sig")]
            Sig = 1
        }


        /// <summary>
        /// Intended use of the public key
        /// </summary>
        /// <value>Intended use of the public key</value>
        [DataMember(Name = "use", EmitDefaultValue = true)]
        public UseEnum? Use { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JwkDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JwkDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JwkDto" /> class.
        /// </summary>
        /// <param name="kid">Key ID uniquely identifying the key (required).</param>
        /// <param name="kty">Key type (e.g., &#39;RSA&#39;, &#39;EC&#39;, &#39;OKP&#39;) (required).</param>
        /// <param name="alg">Algorithm intended for use with the key (required).</param>
        /// <param name="use">Intended use of the public key.</param>
        /// <param name="n">Modulus for RSA keys.</param>
        /// <param name="e">Exponent for RSA keys.</param>
        /// <param name="crv">Curve name for elliptic curve keys.</param>
        /// <param name="x">X coordinate for elliptic curve keys.</param>
        /// <param name="y">Y coordinate for elliptic curve keys.</param>
        public JwkDto(string kid = default, string kty = default, string alg = default, UseEnum? use = default, string n = default, string e = default, string crv = default, string x = default, string y = default)
        {
            // to ensure "kid" is required (not null)
            if (kid == null)
            {
                throw new ArgumentNullException("kid is a required property for JwkDto and cannot be null");
            }
            this.Kid = kid;
            // to ensure "kty" is required (not null)
            if (kty == null)
            {
                throw new ArgumentNullException("kty is a required property for JwkDto and cannot be null");
            }
            this.Kty = kty;
            // to ensure "alg" is required (not null)
            if (alg == null)
            {
                throw new ArgumentNullException("alg is a required property for JwkDto and cannot be null");
            }
            this.Alg = alg;
            this.Use = use;
            this.N = n;
            this.E = e;
            this.Crv = crv;
            this.X = x;
            this.Y = y;
        }

        /// <summary>
        /// Key ID uniquely identifying the key
        /// </summary>
        /// <value>Key ID uniquely identifying the key</value>
        [DataMember(Name = "kid", IsRequired = true, EmitDefaultValue = true)]
        public string Kid { get; set; }

        /// <summary>
        /// Key type (e.g., &#39;RSA&#39;, &#39;EC&#39;, &#39;OKP&#39;)
        /// </summary>
        /// <value>Key type (e.g., &#39;RSA&#39;, &#39;EC&#39;, &#39;OKP&#39;)</value>
        [DataMember(Name = "kty", IsRequired = true, EmitDefaultValue = true)]
        public string Kty { get; set; }

        /// <summary>
        /// Algorithm intended for use with the key
        /// </summary>
        /// <value>Algorithm intended for use with the key</value>
        [DataMember(Name = "alg", IsRequired = true, EmitDefaultValue = true)]
        public string Alg { get; set; }

        /// <summary>
        /// Modulus for RSA keys
        /// </summary>
        /// <value>Modulus for RSA keys</value>
        [DataMember(Name = "n", EmitDefaultValue = true)]
        public string N { get; set; }

        /// <summary>
        /// Exponent for RSA keys
        /// </summary>
        /// <value>Exponent for RSA keys</value>
        [DataMember(Name = "e", EmitDefaultValue = true)]
        public string E { get; set; }

        /// <summary>
        /// Curve name for elliptic curve keys
        /// </summary>
        /// <value>Curve name for elliptic curve keys</value>
        [DataMember(Name = "crv", EmitDefaultValue = true)]
        public string Crv { get; set; }

        /// <summary>
        /// X coordinate for elliptic curve keys
        /// </summary>
        /// <value>X coordinate for elliptic curve keys</value>
        [DataMember(Name = "x", EmitDefaultValue = true)]
        public string X { get; set; }

        /// <summary>
        /// Y coordinate for elliptic curve keys
        /// </summary>
        /// <value>Y coordinate for elliptic curve keys</value>
        [DataMember(Name = "y", EmitDefaultValue = true)]
        public string Y { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JwkDto {\n");
            sb.Append("  Kid: ").Append(Kid).Append("\n");
            sb.Append("  Kty: ").Append(Kty).Append("\n");
            sb.Append("  Alg: ").Append(Alg).Append("\n");
            sb.Append("  Use: ").Append(Use).Append("\n");
            sb.Append("  N: ").Append(N).Append("\n");
            sb.Append("  E: ").Append(E).Append("\n");
            sb.Append("  Crv: ").Append(Crv).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
