/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// LinkedAccountDto
    /// </summary>
    [DataContract(Name = "LinkedAccountDto")]
    public partial class LinkedAccountDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedAccountDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkedAccountDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkedAccountDto" /> class.
        /// </summary>
        /// <param name="id">Unique identifier (required).</param>
        /// <param name="accountId">Account ID (required).</param>
        /// <param name="providerId">Provider ID (e.g., google, github) (required).</param>
        /// <param name="userId">User ID (required).</param>
        /// <param name="accessToken">Access token.</param>
        /// <param name="refreshToken">Refresh token.</param>
        /// <param name="idToken">ID token.</param>
        /// <param name="accessTokenExpiresAt">Access token expires at.</param>
        /// <param name="refreshTokenExpiresAt">Refresh token expires at.</param>
        /// <param name="scope">Scope.</param>
        /// <param name="password">Password.</param>
        /// <param name="createdAt">Creation timestamp (required).</param>
        /// <param name="updatedAt">Last update timestamp (required).</param>
        public LinkedAccountDto(string id = default, string accountId = default, string providerId = default, string userId = default, string accessToken = default, string refreshToken = default, string idToken = default, DateTimeOffset accessTokenExpiresAt = default, DateTimeOffset refreshTokenExpiresAt = default, string scope = default, string password = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LinkedAccountDto and cannot be null");
            }
            this.Id = id;
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for LinkedAccountDto and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "providerId" is required (not null)
            if (providerId == null)
            {
                throw new ArgumentNullException("providerId is a required property for LinkedAccountDto and cannot be null");
            }
            this.ProviderId = providerId;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for LinkedAccountDto and cannot be null");
            }
            this.UserId = userId;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.AccessToken = accessToken;
            this.RefreshToken = refreshToken;
            this.IdToken = idToken;
            this.AccessTokenExpiresAt = accessTokenExpiresAt;
            this.RefreshTokenExpiresAt = refreshTokenExpiresAt;
            this.Scope = scope;
            this.Password = password;
        }

        /// <summary>
        /// Unique identifier
        /// </summary>
        /// <value>Unique identifier</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Account ID
        /// </summary>
        /// <value>Account ID</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Provider ID (e.g., google, github)
        /// </summary>
        /// <value>Provider ID (e.g., google, github)</value>
        [DataMember(Name = "providerId", IsRequired = true, EmitDefaultValue = true)]
        public string ProviderId { get; set; }

        /// <summary>
        /// User ID
        /// </summary>
        /// <value>User ID</value>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Access token
        /// </summary>
        /// <value>Access token</value>
        [DataMember(Name = "accessToken", EmitDefaultValue = false)]
        public string AccessToken { get; set; }

        /// <summary>
        /// Refresh token
        /// </summary>
        /// <value>Refresh token</value>
        [DataMember(Name = "refreshToken", EmitDefaultValue = false)]
        public string RefreshToken { get; set; }

        /// <summary>
        /// ID token
        /// </summary>
        /// <value>ID token</value>
        [DataMember(Name = "idToken", EmitDefaultValue = false)]
        public string IdToken { get; set; }

        /// <summary>
        /// Access token expires at
        /// </summary>
        /// <value>Access token expires at</value>
        [DataMember(Name = "accessTokenExpiresAt", EmitDefaultValue = false)]
        public DateTimeOffset AccessTokenExpiresAt { get; set; }

        /// <summary>
        /// Refresh token expires at
        /// </summary>
        /// <value>Refresh token expires at</value>
        [DataMember(Name = "refreshTokenExpiresAt", EmitDefaultValue = false)]
        public DateTimeOffset RefreshTokenExpiresAt { get; set; }

        /// <summary>
        /// Scope
        /// </summary>
        /// <value>Scope</value>
        [DataMember(Name = "scope", EmitDefaultValue = false)]
        public string Scope { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        /// <value>Password</value>
        [DataMember(Name = "password", EmitDefaultValue = false)]
        public string Password { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        /// <value>Creation timestamp</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Last update timestamp
        /// </summary>
        /// <value>Last update timestamp</value>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkedAccountDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ProviderId: ").Append(ProviderId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  RefreshToken: ").Append(RefreshToken).Append("\n");
            sb.Append("  IdToken: ").Append(IdToken).Append("\n");
            sb.Append("  AccessTokenExpiresAt: ").Append(AccessTokenExpiresAt).Append("\n");
            sb.Append("  RefreshTokenExpiresAt: ").Append(RefreshTokenExpiresAt).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
