/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// PurchaseResponseDto
    /// </summary>
    [DataContract(Name = "PurchaseResponseDto")]
    public partial class PurchaseResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PurchaseResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseResponseDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="merchantId">merchantId (required).</param>
        /// <param name="customerId">customerId (required).</param>
        /// <param name="productId">productId.</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="customerBalanceBefore">customerBalanceBefore.</param>
        /// <param name="customerBalanceAfter">customerBalanceAfter.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public PurchaseResponseDto(string id = default, string merchantId = default, string customerId = default, string productId = default, decimal amount = default, string currency = default, string status = default, decimal customerBalanceBefore = default, decimal customerBalanceAfter = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PurchaseResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantId" is required (not null)
            if (merchantId == null)
            {
                throw new ArgumentNullException("merchantId is a required property for PurchaseResponseDto and cannot be null");
            }
            this.MerchantId = merchantId;
            // to ensure "customerId" is required (not null)
            if (customerId == null)
            {
                throw new ArgumentNullException("customerId is a required property for PurchaseResponseDto and cannot be null");
            }
            this.CustomerId = customerId;
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for PurchaseResponseDto and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for PurchaseResponseDto and cannot be null");
            }
            this.Status = status;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.ProductId = productId;
            this.CustomerBalanceBefore = customerBalanceBefore;
            this.CustomerBalanceAfter = customerBalanceAfter;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customerId", IsRequired = true, EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [DataMember(Name = "productId", EmitDefaultValue = false)]
        public string ProductId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CustomerBalanceBefore
        /// </summary>
        [DataMember(Name = "customerBalanceBefore", EmitDefaultValue = false)]
        public decimal CustomerBalanceBefore { get; set; }

        /// <summary>
        /// Gets or Sets CustomerBalanceAfter
        /// </summary>
        [DataMember(Name = "customerBalanceAfter", EmitDefaultValue = false)]
        public decimal CustomerBalanceAfter { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CustomerBalanceBefore: ").Append(CustomerBalanceBefore).Append("\n");
            sb.Append("  CustomerBalanceAfter: ").Append(CustomerBalanceAfter).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
