/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.8.4
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// SendVerificationEmailDto
    /// </summary>
    [DataContract(Name = "SendVerificationEmailDto")]
    public partial class SendVerificationEmailDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVerificationEmailDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendVerificationEmailDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendVerificationEmailDto" /> class.
        /// </summary>
        /// <param name="email">The email to send verification email to (required).</param>
        /// <param name="callbackURL">The URL to use for email verification callback.</param>
        public SendVerificationEmailDto(string email = default, string callbackURL = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for SendVerificationEmailDto and cannot be null");
            }
            this.Email = email;
            this.CallbackURL = callbackURL;
        }

        /// <summary>
        /// The email to send verification email to
        /// </summary>
        /// <value>The email to send verification email to</value>
        /*
        <example>user@example.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// The URL to use for email verification callback
        /// </summary>
        /// <value>The URL to use for email verification callback</value>
        /*
        <example>https://example.com/callback</example>
        */
        [DataMember(Name = "callbackURL", EmitDefaultValue = false)]
        public string CallbackURL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendVerificationEmailDto {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  CallbackURL: ").Append(CallbackURL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
