/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// SendPhoneOTPDto
    /// </summary>
    [DataContract(Name = "SendPhoneOTPDto")]
    public partial class SendPhoneOTPDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendPhoneOTPDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendPhoneOTPDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendPhoneOTPDto" /> class.
        /// </summary>
        /// <param name="phoneNumber">The phone number to send OTP to (required).</param>
        public SendPhoneOTPDto(string phoneNumber = default)
        {
            // to ensure "phoneNumber" is required (not null)
            if (phoneNumber == null)
            {
                throw new ArgumentNullException("phoneNumber is a required property for SendPhoneOTPDto and cannot be null");
            }
            this.PhoneNumber = phoneNumber;
        }

        /// <summary>
        /// The phone number to send OTP to
        /// </summary>
        /// <value>The phone number to send OTP to</value>
        /*
        <example>+1234567890</example>
        */
        [DataMember(Name = "phoneNumber", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendPhoneOTPDto {\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
