/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// SessionUserDto
    /// </summary>
    [DataContract(Name = "SessionUserDto")]
    public partial class SessionUserDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionUserDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SessionUserDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionUserDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="emailVerified">emailVerified (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="image">image.</param>
        /// <param name="role">role.</param>
        /// <param name="banned">banned.</param>
        /// <param name="banReason">banReason.</param>
        /// <param name="banExpires">banExpires.</param>
        /// <param name="isAnonymous">isAnonymous.</param>
        /// <param name="username">username.</param>
        /// <param name="displayUsername">displayUsername.</param>
        /// <param name="phoneNumber">phoneNumber.</param>
        /// <param name="phoneNumberVerified">phoneNumberVerified.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public SessionUserDto(string id = default, string email = default, bool emailVerified = default, string name = default, string image = default, string role = default, bool banned = default, string banReason = default, DateTimeOffset banExpires = default, bool isAnonymous = default, string username = default, string displayUsername = default, string phoneNumber = default, bool phoneNumberVerified = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SessionUserDto and cannot be null");
            }
            this.Id = id;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for SessionUserDto and cannot be null");
            }
            this.Email = email;
            this.EmailVerified = emailVerified;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for SessionUserDto and cannot be null");
            }
            this.Name = name;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Image = image;
            this.Role = role;
            this.Banned = banned;
            this.BanReason = banReason;
            this.BanExpires = banExpires;
            this.IsAnonymous = isAnonymous;
            this.Username = username;
            this.DisplayUsername = displayUsername;
            this.PhoneNumber = phoneNumber;
            this.PhoneNumberVerified = phoneNumberVerified;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets EmailVerified
        /// </summary>
        [DataMember(Name = "emailVerified", IsRequired = true, EmitDefaultValue = true)]
        public bool EmailVerified { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Image
        /// </summary>
        [DataMember(Name = "image", EmitDefaultValue = false)]
        public string Image { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets Banned
        /// </summary>
        [DataMember(Name = "banned", EmitDefaultValue = true)]
        public bool Banned { get; set; }

        /// <summary>
        /// Gets or Sets BanReason
        /// </summary>
        [DataMember(Name = "banReason", EmitDefaultValue = false)]
        public string BanReason { get; set; }

        /// <summary>
        /// Gets or Sets BanExpires
        /// </summary>
        [DataMember(Name = "banExpires", EmitDefaultValue = false)]
        public DateTimeOffset BanExpires { get; set; }

        /// <summary>
        /// Gets or Sets IsAnonymous
        /// </summary>
        [DataMember(Name = "isAnonymous", EmitDefaultValue = true)]
        public bool IsAnonymous { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets DisplayUsername
        /// </summary>
        [DataMember(Name = "displayUsername", EmitDefaultValue = false)]
        public string DisplayUsername { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumberVerified
        /// </summary>
        [DataMember(Name = "phoneNumberVerified", EmitDefaultValue = true)]
        public bool PhoneNumberVerified { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SessionUserDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  EmailVerified: ").Append(EmailVerified).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Banned: ").Append(Banned).Append("\n");
            sb.Append("  BanReason: ").Append(BanReason).Append("\n");
            sb.Append("  BanExpires: ").Append(BanExpires).Append("\n");
            sb.Append("  IsAnonymous: ").Append(IsAnonymous).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  DisplayUsername: ").Append(DisplayUsername).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  PhoneNumberVerified: ").Append(PhoneNumberVerified).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
