/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// SignUpDto
    /// </summary>
    [DataContract(Name = "SignUpDto")]
    public partial class SignUpDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SignUpDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SignUpDto" /> class.
        /// </summary>
        /// <param name="name">The name of the user (required).</param>
        /// <param name="email">The email address of the user (required).</param>
        /// <param name="password">The password for the user account (required).</param>
        /// <param name="image">Optional URL to the user&#39;s profile image.</param>
        /// <param name="callbackURL">Optional callback URL after successful sign-up.</param>
        /// <param name="rememberMe">Optional flag to indicate if the user should be remembered.</param>
        public SignUpDto(string name = default, string email = default, string password = default, string image = default, string callbackURL = default, bool rememberMe = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for SignUpDto and cannot be null");
            }
            this.Name = name;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for SignUpDto and cannot be null");
            }
            this.Email = email;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for SignUpDto and cannot be null");
            }
            this.Password = password;
            this.Image = image;
            this.CallbackURL = callbackURL;
            this.RememberMe = rememberMe;
        }

        /// <summary>
        /// The name of the user
        /// </summary>
        /// <value>The name of the user</value>
        /*
        <example>John Doe</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The email address of the user
        /// </summary>
        /// <value>The email address of the user</value>
        /*
        <example>john.doe@example.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// The password for the user account
        /// </summary>
        /// <value>The password for the user account</value>
        /*
        <example>StrongPassword123!</example>
        */
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Optional URL to the user&#39;s profile image
        /// </summary>
        /// <value>Optional URL to the user&#39;s profile image</value>
        /*
        <example>https://example.com/avatar.jpg</example>
        */
        [DataMember(Name = "image", EmitDefaultValue = false)]
        public string Image { get; set; }

        /// <summary>
        /// Optional callback URL after successful sign-up
        /// </summary>
        /// <value>Optional callback URL after successful sign-up</value>
        /*
        <example>https://example.com/auth/callback</example>
        */
        [DataMember(Name = "callbackURL", EmitDefaultValue = false)]
        public string CallbackURL { get; set; }

        /// <summary>
        /// Optional flag to indicate if the user should be remembered
        /// </summary>
        /// <value>Optional flag to indicate if the user should be remembered</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "rememberMe", EmitDefaultValue = true)]
        public bool RememberMe { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SignUpDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Image: ").Append(Image).Append("\n");
            sb.Append("  CallbackURL: ").Append(CallbackURL).Append("\n");
            sb.Append("  RememberMe: ").Append(RememberMe).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
