/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.3
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// TransferResponseDto
    /// </summary>
    [DataContract(Name = "TransferResponseDto")]
    public partial class TransferResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransferResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferResponseDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="merchantId">merchantId (required).</param>
        /// <param name="fromCustomerId">fromCustomerId (required).</param>
        /// <param name="toCustomerId">toCustomerId (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="description">description.</param>
        /// <param name="status">status (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public TransferResponseDto(string id = default, string merchantId = default, string fromCustomerId = default, string toCustomerId = default, decimal amount = default, string currency = default, string description = default, string status = default, DateTimeOffset createdAt = default, DateTimeOffset updatedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for TransferResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "merchantId" is required (not null)
            if (merchantId == null)
            {
                throw new ArgumentNullException("merchantId is a required property for TransferResponseDto and cannot be null");
            }
            this.MerchantId = merchantId;
            // to ensure "fromCustomerId" is required (not null)
            if (fromCustomerId == null)
            {
                throw new ArgumentNullException("fromCustomerId is a required property for TransferResponseDto and cannot be null");
            }
            this.FromCustomerId = fromCustomerId;
            // to ensure "toCustomerId" is required (not null)
            if (toCustomerId == null)
            {
                throw new ArgumentNullException("toCustomerId is a required property for TransferResponseDto and cannot be null");
            }
            this.ToCustomerId = toCustomerId;
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for TransferResponseDto and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for TransferResponseDto and cannot be null");
            }
            this.Status = status;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets MerchantId
        /// </summary>
        [DataMember(Name = "merchantId", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantId { get; set; }

        /// <summary>
        /// Gets or Sets FromCustomerId
        /// </summary>
        [DataMember(Name = "fromCustomerId", IsRequired = true, EmitDefaultValue = true)]
        public string FromCustomerId { get; set; }

        /// <summary>
        /// Gets or Sets ToCustomerId
        /// </summary>
        [DataMember(Name = "toCustomerId", IsRequired = true, EmitDefaultValue = true)]
        public string ToCustomerId { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransferResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  MerchantId: ").Append(MerchantId).Append("\n");
            sb.Append("  FromCustomerId: ").Append(FromCustomerId).Append("\n");
            sb.Append("  ToCustomerId: ").Append(ToCustomerId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
