/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// UpdateOrganizationDto
    /// </summary>
    [DataContract(Name = "UpdateOrganizationDto")]
    public partial class UpdateOrganizationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOrganizationDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateOrganizationDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOrganizationDto" /> class.
        /// </summary>
        /// <param name="organizationId">The ID of the organization to update (required).</param>
        /// <param name="data">Data to update (required).</param>
        public UpdateOrganizationDto(string organizationId = default, Object data = default)
        {
            // to ensure "organizationId" is required (not null)
            if (organizationId == null)
            {
                throw new ArgumentNullException("organizationId is a required property for UpdateOrganizationDto and cannot be null");
            }
            this.OrganizationId = organizationId;
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for UpdateOrganizationDto and cannot be null");
            }
            this.Data = data;
        }

        /// <summary>
        /// The ID of the organization to update
        /// </summary>
        /// <value>The ID of the organization to update</value>
        /*
        <example>org_12345</example>
        */
        [DataMember(Name = "organizationId", IsRequired = true, EmitDefaultValue = true)]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Data to update
        /// </summary>
        /// <value>Data to update</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public Object Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateOrganizationDto {\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
