/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// UpdateCustomerDto
    /// </summary>
    [DataContract(Name = "UpdateCustomerDto")]
    public partial class UpdateCustomerDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCustomerDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateCustomerDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCustomerDto" /> class.
        /// </summary>
        /// <param name="email">The email address of the customer.</param>
        /// <param name="name">The full name of the customer.</param>
        /// <param name="metadata">Optional custom metadata (required).</param>
        public UpdateCustomerDto(string email = default, string name = default, Dictionary<string, Object> metadata = default)
        {
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for UpdateCustomerDto and cannot be null");
            }
            this.Metadata = metadata;
            this.Email = email;
            this.Name = name;
        }

        /// <summary>
        /// The email address of the customer
        /// </summary>
        /// <value>The email address of the customer</value>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// The full name of the customer
        /// </summary>
        /// <value>The full name of the customer</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Optional custom metadata
        /// </summary>
        /// <value>Optional custom metadata</value>
        /*
        <example>{&quot;customField&quot;:&quot;value&quot;,&quot;orderId&quot;:&quot;12345&quot;}</example>
        */
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCustomerDto {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
