/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cashful.Client.FileParameter;
using OpenAPIDateConverter = Cashful.Client.OpenAPIDateConverter;

namespace Cashful.Model
{
    /// <summary>
    /// VerifyApiKeyDto
    /// </summary>
    [DataContract(Name = "VerifyApiKeyDto")]
    public partial class VerifyApiKeyDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyApiKeyDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VerifyApiKeyDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyApiKeyDto" /> class.
        /// </summary>
        /// <param name="key">The API key to verify (required).</param>
        public VerifyApiKeyDto(string key = default)
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for VerifyApiKeyDto and cannot be null");
            }
            this.Key = key;
        }

        /// <summary>
        /// The API key to verify
        /// </summary>
        /// <value>The API key to verify</value>
        /*
        <example>pk_live_12345...</example>
        */
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VerifyApiKeyDto {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
