/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cashful.Sdk.Client;
using Cashful.Sdk.Api;

namespace Cashful.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing HealthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class HealthApiTests : IDisposable
    {
        private HealthApi instance;

        public HealthApiTests()
        {
            instance = new HealthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HealthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' HealthApi
            //Assert.IsType<HealthApi>(instance);
        }

        /// <summary>
        /// Test CheckHealth
        /// </summary>
        [Fact]
        public void CheckHealthTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CheckHealth();
            //Assert.IsType<Object>(response);
        }
    }
}
