/*
 * Cashful API
 *
 * Developer documentation for the Cashful platform.
 *
 * The version of the OpenAPI document: 0.6.2
 * Contact: support@cashful.africa
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cashful.Sdk.Client;
using Cashful.Sdk.Api;
// uncomment below to import models
//using Cashful.Sdk.Model;

namespace Cashful.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing PaymentIntentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentIntentsApiTests : IDisposable
    {
        private PaymentIntentsApi instance;

        public PaymentIntentsApiTests()
        {
            instance = new PaymentIntentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentIntentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PaymentIntentsApi
            //Assert.IsType<PaymentIntentsApi>(instance);
        }

        /// <summary>
        /// Test CancelPaymentIntent
        /// </summary>
        [Fact]
        public void CancelPaymentIntentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.CancelPaymentIntent(id);
            //Assert.IsType<PaymentIntentResponseDto>(response);
        }

        /// <summary>
        /// Test ConfirmPaymentIntent
        /// </summary>
        [Fact]
        public void ConfirmPaymentIntentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ConfirmPaymentIntent(id);
            //Assert.IsType<PaymentIntentResponseDto>(response);
        }

        /// <summary>
        /// Test CreatePaymentIntent
        /// </summary>
        [Fact]
        public void CreatePaymentIntentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreatePaymentIntentDto createPaymentIntentDto = null;
            //var response = instance.CreatePaymentIntent(createPaymentIntentDto);
            //Assert.IsType<PaymentIntentResponseDto>(response);
        }

        /// <summary>
        /// Test ListPaymentIntents
        /// </summary>
        [Fact]
        public void ListPaymentIntentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string merchantId = null;
            //decimal? limit = null;
            //decimal? offset = null;
            //string? status = null;
            //instance.ListPaymentIntents(merchantId, limit, offset, status);
        }

        /// <summary>
        /// Test RetrievePaymentIntent
        /// </summary>
        [Fact]
        public void RetrievePaymentIntentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RetrievePaymentIntent(id);
            //Assert.IsType<PaymentIntentResponseDto>(response);
        }
    }
}
